### ISSUE TITLE
Import db dump from cloud environment (e.g. integration)

### ISSUE THREAD

**Issue by cdtweb** [magento/magento-cloud-docker#10]
Hi! One of the things stopping my team from utilizing this project is that there isn't an obvious way for us to have the database be created from a dump file. 

```
magento-cloud db:dump -p xxxxxxxx -e integration
```

It appears that it is creating the database from scratch.. Any help you can provide would really be appreciated. For now, we are stuck using a slower, but full featured Vagrant VM that we built in house.

**Comment by shiftedreality** [comment]
Hi,

Currently, there is no possibility to import DB. I've created internal ticket MAGECLOUD-2577 and hopefully, we will add this feature in next release.

**Comment by iamface** [comment]
I have this same issue. Was this Docker environment ready for release? It feels like much needed features are still being worked on and it wasn't ready.

**Comment by shiftedreality** [comment]
@iamface it's a very new feature, but we just release an update with Varnish, Redis, read-only FS and more user-friendly configs https://devdocs.magento.com/guides/v2.2/cloud/release-notes/cloud-tools.html

**Comment by shiftedreality** [comment]
https://devdocs.magento.com/guides/v2.3/cloud/docker/docker-development.html#database-container

This feature was added to Docker for Cloud in recent releases. Closed.
