### ISSUE TITLE
Platform-agnostic Docker builder

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#102]
To expand Cloud Docker presence and align wit platform-agnostic vision of ECE-Tools we should provide a non-Magento-Cloud way to install Docker so developers with own infrastructure could use it.

**Comment by mattskr** [comment]
The following is a list of files we found are needed from the magento-cloud repo in order to get it work for a non-cloud project for example:

```
.magento/
        /routes.yaml
        /services.yaml
.magento.app.yaml
auth.json
composer.json
magento-vars.php
php.ini
```

**Comment by YPyltiai** [comment]
**Additional grooming notes (11/13/2019):**
- Would be great to have default configurations mapped to Magento versions, so we don't need Cloud-specific files to be in place (no need to pull remote as a pre-requisite)
- Overrides should still be supported but more as an exception than as a common flow. Currently any custom environment can be built only by hand-writing all versions & parameters into CLI command
- Agreed that developer shouldn't be specifying exact versions unless some very specific environment is required

**Comment by shiftedreality** [comment]
Internal task: https://magento2.atlassian.net/browse/MAGECLOUD-5185
