### ISSUE TITLE
Add Multi-website Support into Cloud Docker

### ISSUE THREAD

**Issue by nmklong** [magento/magento-cloud-docker#104]
I'm using this docker to add another website to my local, however i keep getting redirected back to http://magento2.docker/

My magento project is currently using Magento 2.2.5

### Steps to reproduce
1. Start the magento cloud docker, set to developer deploy mode following this tutorial: https://devdocs.magento.com/guides/v2.3/cloud/docker/docker-config.html
2. Set up a new website, store, store view and use this tutorial to set up a new website: https://devdocs.magento.com/guides/v2.3/cloud/project/project-multi-sites.html
3. Assuming we plan to have `http://second.magento2.docker/` for the new website that i'm adding, i also added this to hosts file:
```
127.0.0.1 magento2.docker
127.0.0.1 second.magento2.docker
```
4. Updated base url for the new website, re-deployed, cleared caches

### Expected result

1. Going to `http://second.magento2.docker/` should show the second website that was set up

### Actual result

1. Going to `http://second.magento2.docker/` keeps redirecting back to `http://magento2.docker`, showing the old website

**Comment by YPyltiai** [comment]
Hi @nmklong ,

Thanks for opening this issue. We will review this scenario and will get back to you.

Thanks,
Yevhenii

**Comment by shiftedreality** [comment]
For developer: To start with https://github.com/magento/magento-cloud/blob/master/magento-vars.php file and inject it to `php.ini` configuration file

**Comment by YPyltiai** [comment]
@aepod is starting work on this one.

**Comment by andriyShevtsov** [comment]
Created internal task MAGECLOUD-5584

**Comment by shiftedreality** [comment]
This is currently breaking the images: https://github.com/magento/ece-tools/pull/702/checks?check_run_id=523094586

It looks like there is something specific to our FPM containers, re-opening

**Comment by shiftedreality** [comment]
JIRA issue: https://jira.corp.magento.com/browse/MCLOUD-5511

**Comment by shiftedreality** [comment]
Corresponding DevDocs PR: https://github.com/magento/devdocs/pull/7646
