### ISSUE TITLE
Varnish disrupts use of xdebug

### ISSUE THREAD

**Issue by aepod** [magento/magento-cloud-docker#110]
Varnish is making it so xdebug is not working correctly.

### Preconditions
1.  Xdebug is on
2.  Varnish is enabled

### Steps to reproduce
1. Xdebug request do not connect, unless you restart varnish. Only first request (uncached) will work

### Expected result
1. Every request with the cookie should work

**Comment by shiftedreality** [comment]
PR was merged, closed.
