### ISSUE TITLE
xDebug enabled and pre-configured in Developer mode

### ISSUE THREAD

**Issue by joeshelton-wagento** [magento/magento-cloud-docker#112]
xDebug is a critical feature of a development environment. But, it use is often intended only for the local development environment. Currently to enable xDebug in the Cloud Docker, a Cloud configuration file needs to be modified. (.magento.app.yaml) In the most common use-case for utilizing xDebux developers will want it enabled locally while developing or troubleshooting an issue, but do not intend for it to be enabled in the Cloud environment. This causes them to continually have to configure and "unconfigure" xDebug before and after committing code.

### Preconditions
A development task that requires xDebug use locally.
No intention to have xDebug enabled in the Cloud environment.

### Steps to reproduce
Configure local Cloud docker to use xDebug.
Use xDebug to solve an issue.
"Unconfigure" xDebug.
Commit code, create pull request.

### Expected result
Developer should not have to configure and "unconfigure" xDebug per issue.

### Actual result
Developer has to configure and "unconfigure" xDebug per issue. (In a large organization, developers will inevitably forget to do this occasionally, causing xDebug to be inadvertently enabled in the Cloud environment.)

**Comment by di-ivanov** [comment]
As a follow up to our slack discussion with @joeshelton-wagento . 
On a custom set of docker containers, I've implemented two different approaches. both of them work, and probably there are even more:

1. Script that switches xdebug on the fly. Your php container is deployed with all needed configuration for xdebug, only with the first line in xdebug.ini commented
/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini  
   ```
   ;zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20180731/xdebug.so
   xdebug.idekey=${XDEBUG_IDEKEY}
   xdebug.remote_log=/tmp/xdebug.log
   ...  
   ```
   Whenever you want to start debuging you just execute the following command:
`docker exec -it $(docker-compose ps -q fpm | awk '{print $1}') sh -c "sed -i 's zend_extension ;zend_extension ' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && kill -USR2 1"
`
The command runs in your container removes the commented line that loads xdebug extension and then restarts the php-fpm inside the container. The command is for Alpine based containers.
What are the pluses of this approach - it has a minimum impact on architecture, and the subsequent command can be added easily to bin/magento similar script. Minuses -  it's a hacky approach, and still requires a command before starting debugging.

2. Use two php containers one without xdebug and one with. Switch them based on the request in nginx config like:
   ```
   map $cookie_XDEBUG_SESSION $fpm_fastcgi_pass {
    default fpm:9000;
    PHPSTORM fpm_xdebug:9000;
   }
   ```
   Pluses - simplifies greatly debugging you have a single control point - the cookie, allows you to minimise the xdebug config and just keep it always enabled, no host games.
Minus - it requires some architectural changes.

My personal preference and current tool is B - two containers.

**Comment by aepod** [comment]
The second method is much better. Xdebug slows down PHP quite a bit. SCD went from 3 minutes to over 6 minutes (more than double) by just enabling xdebug.

Limiting xdebug to the fpm container, and making a second one so that most requests can be not hindered by it is a great idea. Even having the php module enabled is enough, you do not even need to have it configured to see the slowness.

**Comment by YPyltiai** [comment]
Related PR: #122

**Comment by YPyltiai** [comment]
Completed in #122
