### ISSUE TITLE
Make native sync the default sync in Developer mode

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#114]
During last grooming, we agreed to have native mode the default one so no additional tools needed. Later SI can choose the tool which they need.

### Preconditions

1. Magento is cloned locally 

### Steps to reproduce

1. Generate docker-compose in Developer mode

### Expected result

1. The default mode us `--native`

### Actual result

1. The default mode is `docker-sync`

**Comment by andriyShevtsov** [comment]
Created internal task https://magento2.atlassian.net/browse/MAGECLOUD-5066

**Comment by andriyShevtsov** [comment]
QA approved

**Comment by YPyltiai** [comment]
Completed in #124
