### ISSUE TITLE
MCLOUD-5752: Add additional healthchecks

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#116]
[MCLOUD-5752](https://jira.corp.magento.com/browse/MCLOUD-5752)
In PR https://github.com/magento/magento-cloud-docker/pull/113 we've added the concept of health checks and ES health checks as basic ones. The health checks should be added for other services as well.

## AC
* Add health checks for next services:
   * PHP-FPM
   * MySQL
   * Redis
   * RabbitMQ

**Comment by VisanthSampath** [comment]
Hi Team,
I have been trying to add a health check to RabbitMQ container. I am using the rabbitmq-diagnostics for checking the health of the container.

But when I try rabbitmq-diagnostics -q node_health_check, the command throws an error in the container stating that the node is not found.
How to proceed further on this. @shiftedreality
