### ISSUE TITLE
Import DB instructions not working

### ISSUE THREAD

**Issue by vbuck** [magento/magento-cloud-docker#12]
According to recent documentation published in the README, and to reference related issue #10, I tried this import procedure but encountered a failure:

```
Starting XXXX_appdata_1 ... done
Starting XXXX_dbdata_1  ... done
Starting XXXX_redis_1   ... done
Starting XXXX_db_1      ... done
[ ok ] Starting enhanced syslogd: rsyslogd.
Deploying Magento Cloud...
[2018-09-26 00:35:19] NOTICE: Starting deploy. (magento/ece-tools version: 2002.0.13, magento/magento2-base version: 2.2.6)  
[2018-09-26 00:35:19] INFO: Starting pre-deploy.  
[2018-09-26 00:35:19] INFO: Skip copying directory ./var/view_preprocessed.  
[2018-09-26 00:35:19] INFO: Clearing ./var/view_preprocessed  
[2018-09-26 00:35:19] INFO: Clearing redis cache  
[2018-09-26 00:35:19] INFO: redis-cli -h redis -p 6379 -n 1 flushdb  
[2018-09-26 00:35:19] INFO: Recoverable directories were copied back.  
[2018-09-26 00:35:19] INFO: Disable cron  
[2018-09-26 00:35:19] INFO: Trying to kill running cron jobs  
[2018-09-26 00:35:19] INFO: exec pgrep -f 'bin/magento cron:run'  
[2018-09-26 00:35:19] INFO: Running Magento cron processes were not found.  
[2018-09-26 00:35:19] INFO: Validating configuration  
[2018-09-26 00:35:19] INFO: Checking if db exists and has tables  
[2018-09-26 00:35:19] INFO: Set flag: var/.deploy_is_failed  
[2018-09-26 00:35:19] CRITICAL: SQLSTATE[HY000] [2002] Connection refused  

                                             
  [PDOException]                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

deploy
```

I see that you pulled this tip from the corresponding Docker image feature:
> https://github.com/docker-library/mariadb/blob/master/10.0/docker-entrypoint.sh#L169

Now I see that my SQL file has been mounted if I run:

```
docker-compose run db bash -c "ls -larth /docker-entrypoint-initdb.d/"
```

But something about this fails to run when the container is started. Do you have any thoughts on what could be causing this issue? In the meantime I'm researching the behavior of this container and its companion initialization script `/docker-entrypoint.sh`.

**Comment by shiftedreality** [comment]
I had to recreate containers to provision configs and make it work. Not sure about already started containers.

**Comment by vbuck** [comment]
Ok. I still haven't been able to sort this out. In my case, the DB dump was rather large (6GB), which I selected intentionally to see how it would fare. It was a complete Magento 2 snapshot. And each time I tried to resolve this I would recreate the containers, according to:

> https://devdocs.magento.com/guides/v2.2/cloud/reference/docker-config.html
> Following `v2002.0.13` instructions

Also, I noticed that `ece-tools`, during the deploy phase, via `\Magento\MagentoCloud\Process\Deploy\InstallUpdate\Install\Setup::execute` will arbitrarily specify the `timezone` and the `cleanup-database` flags, which results in the DB being dropped. 

So I'm assuming the DB pre-load you prescribe happens after this is run? In the meantime, I'm able to work around the issue with a custom post-run command:

**Mount the DB snapshot to a custom path in the `db` service's `volumes` entry**

    db:
      image: 'mariadb:10'
      ports:
        …
      volumes_from:
        …
      environment:
        …
      volumes:
        - './db.sql.gz:/magento-preload/db.sql.gz'

**Import from the mount path after the container has been deployed**

    docker-compose run db bash -c \
        "gzip -dc /magento-preload/db.sql.gz | mysql -umagento2 -pmagento2 -hdb magento2"

But I'm still interested in the most appropriate solution. Anybody else running into issues with this?

**Comment by shiftedreality** [comment]
ECE-Tools won't clean DB if it contains `core_config_data` or `setup_modules` tables (`\Magento\MagentoCloud\Config\State::isInstalled`), upgrade process will be triggered instead.

**Comment by vbuck** [comment]
Thanks for clarifying. I'm going to close this issue for now. Given my workaround and your report of having no issues with import on your end, I may be doing something wrong. I'll follow up if I ever decide to come back to the standard instructions.

**Comment by shiftedreality** [comment]
I will be very grateful if you create PR with your instruction, it can be useful as well

**Comment by david-kominek** [comment]
I have found that removing the magento-db volume triggers the rebuild of the database from the db backup in .docker/mysql/docker-entrypoint-initdb.d.

A big warning here, this irrevocably deletes all the data in your docker environment, so a database dump on the docker environment would be advised.
