### ISSUE TITLE
Cron container stops after starting on 1.0 images

### ISSUE THREAD

**Issue by sorinsugar** [magento/magento-cloud-docker#132]
The cron container exists after starting.

### Preconditions
1. Use 1.0 docker images (or 1.1)

### Steps to reproduce
1. Run docker-compose up -d 

### Expected result
1. Cron container starts and runs in the background

### Actual result
1. Cron container exits after some seconds
```
$ docker logs local_cron_1
Updating www uid and gid
Docker: uid = 1000, gid = 1000
Incumbent: user = www, group = www
Starting Mail Transport Agent (MTA): sendmail.
tail: cannot open '/var/log/cron.log' for reading: No such file or directory
tail: no files remaining
```
From what I can see, the lines `CRON_LOG=/var/log/cron.log` and  `touch $CRON_LOG` were deleted in the 1.0 tags (and 1.1) docker-entrypoint.sh scripts.
Was there a reason for that?

**Comment by shiftedreality** [comment]
This clearly looks like a mistake.

I've created an internal ticket https://magento2.atlassian.net/browse/MAGECLOUD-5063

Please feel free to create a PR for this issue.

**Comment by shiftedreality** [comment]
Fixed in https://github.com/magento/magento-cloud-docker/pull/133 for 1.0 branch and will be ported into develop
