### ISSUE TITLE
MCLOUD-5982: Remove PHP requirement for Docker configuration build

### ISSUE THREAD

**Issue by joeshelton-wagento** [magento/magento-cloud-docker#148]
https://jira.corp.magento.com/browse/MCLOUD-5982:
Remove any PHP requirement that is present for building docker configuration. Many in the community have a concern about this. I think it would improve usability, and also more closely resemble other community Docker configurations. Potentially it would be more fail-safe.

Potential solutions:
Simplify the logic of configuration builds until it is appropriate for a bash script.
Pre-generate all possible configurations in a subfolder and create a "docker-compose.yml" symlink to the appropriate one during build.
Use the bin/docker interface to load configuration stubs for all required services during build. (Could the build process be completely eliminated using this methodology?)

**Comment by aepod** [comment]
It is very easy to run the generate in a docker container, which follows
best practices. There is nothing stopping end users from generating all of
the configs they need, it is a bit of a snowflake issue more than anything
else.

docker run -it  -v $(pwd):/app/ -v ~/.composer/:/root/.composer/ magento/magento-cloud-docker-php:7.3-cli-1.1 bash -c "./vendor/bin/ece-docker build:compose --es=7.2 --sync-engine=native"

This builds without the PHP requirement in the OS. So really this already
is solved in some ways.

This method is in the devdocs now:
https://devdocs.magento.com/cloud/docker/docker-config.html#running-composer-with-docker
But it is in the context of composer (which actually has to happen before
you run the ece-docker command)

**Comment by YPyltiai** [comment]
@michaelcasey316 , assigning to you since you work on it already.

**Comment by shiftedreality** [comment]
Story: https://magento2.atlassian.net/browse/MAGECLOUD-3243

**Comment by joeshelton-wagento** [comment]
Those commands are clever, @aepod , but I don't think the majority of the community would intuitively use them. The Docker configuration build is a critical first step at which if people are confused, they will abandon this solution for the other available Magento 2 Docker configurations. I'm in favor simplifying/eliminating the build process. Or, at least adding the commands you mentioned to the bin/docker CLI so they are more available to people.

**Comment by aepod** [comment]
I love the idea of making CLI commands to do this, but was not sure where
to put it.

1) Cloud docker project, not possible it would not be instanced yet.
2) Ece-tools same problem (needs composer)
3) Cloud Template, would work I suppose but didn't seem right.

Let me know where to put it, we can script this out in bash and have this
possible to run the commands :)

**Comment by michaelcasey316** [comment]
This issue also relates to https://github.com/magento/magento-cloud-docker/issues/47

**Comment by andriyShevtsov** [comment]
Related PR approved and will be targeted to 1.0.2 version
