### ISSUE TITLE
Can I use these config on Kunbernetes instead of on docker-compose?

### ISSUE THREAD

**Issue by zhulinwei** [magento/magento-cloud-docker#152]
I find [magento2-kubernetes-devbox](https://github.com/magento/magento2-kubernetes-devbox), but I would like to use AWS EKS deploy magento on kubernetes instead of minikube. 
Can I use [magento-cloud-docker](https://github.com/magento/magento-cloud-docker) on kubernetes?

**Comment by YPyltiai** [comment]
@shiftedreality , please confirm.

**Comment by shiftedreality** [comment]
Hello, it is not supported OOTB.

You can probably use the images for custom K8s setup.
Feel free to add such functionality or provide your vision how would you see this, so we can add a task to the backlog.

**Comment by zhulinwei** [comment]
> Hello, it is not supported OOTB.
> 
> You can probably use the images for custom K8s setup.
> Feel free to add such functionality or provide your vision how would you see this, so we can add a task to the backlog.

Thanks you.
