### ISSUE TITLE
[Doc] Adding new PHP extensions

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#155]
This task should cover the process of adding a new PHP extension to PHP images of Cloud Docker.

**AC**
* PR with the topic is delivered to DevDocs

**Comment by meker12** [comment]
@shiftedreality  Is this for adding the pcov extension?

**Comment by shiftedreality** [comment]
This is a task to describe the abstract process of adding new PHP extension

**Comment by meker12** [comment]
We have some info in the docs already that can be expanded:

https://devdocs.magento.com/cloud/docker/docker-containers-service.html#fpm-container

![image](https://user-images.githubusercontent.com/6391769/75282267-61951700-57d6-11ea-8efe-001b55e99ee3.png)

**Comment by arhiopterecs** [comment]
The internal ticket was created https://jira.corp.magento.com/browse/MCLOUD-6998
