### ISSUE TITLE
Official and supported?

### ISSUE THREAD

**Issue by brandontamm** [magento/magento-cloud-docker#16]
Does Magento support this project officially? If we have enterprise level support - would magento support answer questions and provide guidance to using this cloud version of docker

**Comment by shiftedreality** [comment]
Closed

**Comment by brandontamm** [comment]
So to rehash, this project is meant to support users of magento cloud-based version...but we could technically use the container-based approach in local and production with modification and no support?

any plans to eventually roll this or any docker-based projects into supported versions?

I ask because I've been using docker-compose and composer.json to manage magento projects since magento 1.9 and, even with professional support, have always gotten a refusal from support to troubleshoot even basic magento questions because of my use of containerized approach.
