### ISSUE TITLE
Unable to enable sending email in the docker

### ISSUE THREAD

**Issue by nmklong** [magento/magento-cloud-docker#176]
https://jira.corp.magento.com/browse/MCLOUD-5624:
### Steps to reproduce
i added `ENABLE_SENDMAIL=true` in `fpm/environment` of `docker-compose.yml` but it’s still not sending emails.

Was following the direction at the bottom of this page:
https://devdocs.magento.com/cloud/docker/docker-config.html

**Comment by shiftedreality** [comment]
@nmklong could you try adding this env to `generic` container?

**Comment by nmklong** [comment]
@shiftedreality thanks for the suggestion, i will try that, after adding do i need to remove all containers and create them all again? as it's being extended by all of them, i'm using mutagen and it takes a while to resync all the files so just wanted to avoid that. Will have to if there's no other way

**Comment by shiftedreality** [comment]
Yes, changing variables requires `docker-compose down`. You don't need to use `-v` option, so your volumes will remain

**Comment by andriyShevtsov** [comment]
For me it doesn't work

**Comment by nmklong** [comment]
It's now throwing an "internal error" message to me, removing the flag will be working fine again. I'm unable to trace down what kind of error as Magento logs don't seem log anything related to that, as well as `var/report`

**Comment by shiftedreality** [comment]
Andrii confirmed that it does not work for him as well.
Created internal ticket: https://jira.corp.magento.com/browse/MCLOUD-5624

**Comment by sorinsugar** [comment]
As a workaround, we've added a mailcatcher image to the compose file and a volume to fpm/cron containers with a config file in which we point sendmail SMART_HOST to mailcatcher. Adding a hostname to fpm greatly improves the time it takes for sendmail to perform the handshake with mailcatcher.

Override compose file:
```
cron:
    volumes:
      - './.docker/mnt/configs/provider.m4:/etc/mail/m4/provider.m4'
```
Contents of the provider.m4 file is as follows:

> define(\`SMART_HOST', \`mailcatcher')dnl

The 'mailcatcher' string in the above file is the name of the mailcatcher service we're using.
