### ISSUE TITLE
MCLOUD-5981: How to Install and Configure Gnupg ?

### ISSUE THREAD

**Issue by eladius1129** [magento/magento-cloud-docker#177]
https://jira.corp.magento.com/browse/MCLOUD-5981:
I am trying to use **gpg** command with **shell_exec ('command -v gpg')** and the result is **null,** how to configure my docker to be able to use **gpg** command?

**Comment by shiftedreality** [comment]
Hello, it looks like we currently don't support this extension in our PHP images.

You can add it in a similar way as https://github.com/magento/magento-cloud-docker/pull/136
