### ISSUE TITLE
Add Elasticsearch 7.6 

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#216]
**Is your feature request related to a problem? Please describe.**
Since Magento 2.4 will support ES 7.6, we should add support to our services stack

**Describe the solution you'd like**
* ES 7.6 is added

**Comment by andriyShevtsov** [comment]
Internal issue https://jira.corp.magento.com/browse/MCLOUD-6013

**Comment by G-Arvind** [comment]
Hi @shiftedreality, I belive ES 7.6 images are already added in this PR https://github.com/magento/magento-cloud-docker/pull/205 which addresses this issue https://github.com/magento/magento-cloud-docker/issues/201.

Thanks

**Comment by shiftedreality** [comment]
Yeap missed that.

Thank you!
