### ISSUE TITLE
Add Git/JIRA sync

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento-cloud-docker#230]
Board: https://jira.corp.magento.com/browse/MCLOUD

Projects:
* <https://github.com/magento/ece-tools]
* [https://github.com/magento/magento-cloud-docker>

Test again

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MCLOUD-5611

**Comment by shiftedreality** [comment]
Test
