### ISSUE TITLE
MCLOUD-6453 : ERROR: elasticsearch: condition: service_healthy

### ISSUE THREAD

**Issue by itsazzad** [magento/magento-cloud-docker#231]
https://jira.corp.magento.com/browse/MCLOUD-6453: 
I am encountering errors while bringing up the project.
```
ERROR: for deploy  Container "b252635da267" is unhealthy.

ERROR: for build  Container "b252635da267" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```
But working with:
```
      elasticsearch:
        condition: service_started
```

**Comment by YPyltiai** [comment]
Hi @itsazzad ,

Thanks for posting the bug report.
@aepod , is that the same issue you mentioned in Slack?

Thanks,
Yevhenii

**Comment by mveeramneni** [comment]
@magento export issue to Jira project MCLOUD as Bug

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-6453) is successfully created for this issue.

**Comment by lbortolotto-jakala** [comment]
Hi, is there any workaround?
Thanks!

**Comment by arhiopterecs** [comment]
@itsazzad, @lbortolotto-jakala 
Hi!
I tried to reproduce this but unsuccessfully.
```
docker-compose ps
            Name                           Command                  State                           Ports
-----------------------------------------------------------------------------------------------------------------------------
....
magento-cloud_elasticsearch_1   /usr/local/bin/docker-entr ...   Up (healthy)   9200/tcp, 9300/tcp
....
```
```
docker image ls
REPOSITORY                                   TAG                 IMAGE ID            CREATED             SIZE
....
magento/magento-cloud-docker-elasticsearch   6.5-1.1             a4f3770bb878        3 months ago        787MB
....
```
```
Darwin       
Docker version 19.03.12, build 48a66213fe
docker-compose version 1.27.2, build 18f557f9
docker-credential-desktop version 0.6.3
```
Are you still seeing this behavior?
If you are using Linux the following command can help you:
sudo sysctl -w vm.max_map_count=262144;

**Comment by andriyShevtsov** [comment]
I don't think issue still exist
@itsazzad @lbortolotto-jakala  did you tried with recently released docker?

**Comment by jayachandraoggy** [comment]
> @itsazzad, @lbortolotto-jakala
> Hi!
> I tried to reproduce this but unsuccessfully.
> 
> ```
> docker-compose ps
>             Name                           Command                  State                           Ports
> -----------------------------------------------------------------------------------------------------------------------------
> ....
> magento-cloud_elasticsearch_1   /usr/local/bin/docker-entr ...   Up (healthy)   9200/tcp, 9300/tcp
> ....
> ```
> 
> ```
> docker image ls
> REPOSITORY                                   TAG                 IMAGE ID            CREATED             SIZE
> ....
> magento/magento-cloud-docker-elasticsearch   6.5-1.1             a4f3770bb878        3 months ago        787MB
> ....
> ```
> 
> ```
> Darwin       
> Docker version 19.03.12, build 48a66213fe
> docker-compose version 1.27.2, build 18f557f9
> docker-credential-desktop version 0.6.3
> ```
> 
> Are you still seeing this behavior?
> If you are using Linux the following command can help you:
> sudo sysctl -w vm.max_map_count=262144;

Thanks @arhiopterecs

This command helped me.
- sudo sysctl -w vm.max_map_count=262144;

**Comment by lbortolotto-jakala** [comment]
yes, we fixed the problem with this commands
```
echo fs.inotify.max_user_watches=100000 | sudo tee -a /etc/sysctl.conf
sudo sysctl -w vm.max_map_count=262144
echo "vm.max_map_count=262144" >> /etc/sysctl.conf
sudo sysctl -p
```

**Comment by arhiopterecs** [comment]
@lbortolotto-jakala , @jayachandraoggy 
Please describe the configuration in which you encountered this error
OS, version
Docker version

**Comment by jayachandraoggy** [comment]
> @lbortolotto-jakala , @jayachandraoggy
> Please describe the configuration in which you encountered this error
> OS, version
> Docker version

OS - Ubuntu 20.04 lts
Docker version 19.03.13, build 4484c46d9d

**Comment by danico90** [comment]
I solved this temporarily on Mac by increasing the memory Docker uses from 2GB to 4GB.
