### ISSUE TITLE
MCLOUD-6430: Xdebug not working on Magento Cloud Docker 1.1

### ISSUE THREAD

**Issue by drpayyne** [magento/magento-cloud-docker#233]
https://jira.corp.magento.com/browse/MCLOUD-6430:

### Preconditions
-  Linux machine (Ubuntu `18.10`, or equivalent)
-  Latest versions of Magento (`2.3.5`), cloud-docker (`1.1.0`), and ece-tools (`2002.1.1`)
-  Intent to debug using Xdebug

### Steps to reproduce
1. Follow [Configure Xdebug for Docker](https://devdocs.magento.com/cloud/docker/docker-development-debug.html) to set up Xdebug configurations and containers
2. Attempt to debug using Xdebug
3. Fail at debugging

### Expected result
-  To be able to listen on the xdebug port and stop at set breakpoints to debug

### Actual result
-  PhpStorm throws an error saying `Port is busy` when starting to listen for connections
-  PhpStorm doesn't actually stop at breakpoints.

### More Information

I had requested some assistance regarding this on the `cloud-docker` channel in Magento Slack, and [Damien Retzinger](https://magentocommeng.slack.com/team/UDS2XN0SV) reached out and we were able to get this working after an hour of debugging, but with workarounds. Here are our discoveries and how we fixed them.

1.  The IDE throws an error saying `Port is busy` as the same port is exposed by the `fpm_xdebug` container.

2.  Xdebug is not even loaded by default in the `fpm_xdebug` container. (???)

3. `host.docker.internal`, which is set as the `remote_host` for Xdebug configuration is unresolvable in a Linux Docker container (More on that here: https://github.com/docker/for-linux/issues/264).
    ```
    root@fpm_xdebug:/app# curl host.docker.internal
    curl: (6) Could not resolve host: host.docker.internal
    ```

-  Issue No. 1 can be resolved by not exposing ports from the `fpm_xdebug` container.

-  We resolved issue No. 2 by adding `xdebug` to the list of PHP extensions under the key `fpm_xdebug.environment`'s `PHP_EXTENSIONS` environment variable in the `docker-compose.yml` file like so: 
    ```
      fpm_xdebug:
        ...
        environment:
          - 'PHP_EXTENSIONS=bcmath bz2 calendar ... xsl sodium xdebug'
    ```

-  Regarding issue No. 3, this is something more complex:
    -  We had to first install the `ip` command inside the `fpm_xdebug` container by running `apt-get update` followed by `apt-get install iproute2`.
    -  We then got the `remote_host` IP by running `/sbin/ip route|awk '/default/ { print $3 }'`.
    -  Replacing `XDEBUG_CONFIG=remote_host=host.docker.internal` with `XDEBUG_CONFIG=remote_host=<ip-obtained-from-inside-the-xdebug-container> remote_port=9002` (without the quotes, unlike the one in DevDocs, since adding quotes does not work) in the `.docker/php.env` file got xdebug ready to debug.
    -  Set the same port in PhpStorm/VS Code's Xdebug port settings.

-  An alternative `remote_host` IP we used to get Xdebug working was by using the Docker Bridge IP. Run `docker network inspect bridge --format='{{( index .IPAM.Config 0).Gateway}}'` to get the same, and update the `remote_host` IP in the `.docker/php.env` file. Don't forget to rebuild your containers!

> **There's got to be some way to automate this instead of adding a few more steps for the developer to perform to be able to debug.**

**Comment by joeshelton-wagento** [comment]
Issue 1 and 2 should be addressed ASAP, perhaps separate from 3.

1 - Docker has to refrain from binding any ports on the host machine for Xdebug purposes. The IDE needs to bind there. The current "9001:9001" port binding in Docker isn't a part of any viable Xdebug configuration that I can think of. This is going to confuse people quite a bit.

3 is a problem, but not a new problem. We've been dealing with this all along. Until Docker has a consistent cross-OS way to address the host machine, there's no easy solution.

Here's a build command that produces the issues above:
`vendor/bin/ece-docker build:compose --mode=developer --sync-engine=native --no-varnish`

**Comment by drpayyne** [comment]
Related issue: https://github.com/magento/devdocs/issues/7400

**Comment by YPyltiai** [comment]
@drpayyne , @carlos-reynosa, would the documentation update solve this short-term? I still think that we need OS-specific override reference files to be provided to fix these kind of issues. This doesn't exist now though, which makes fixing it harder.

**Comment by drpayyne** [comment]
Hi @YPyltiai, a documentation update would solve problem 3, but not 1 and 2 described in the description above. As @joeshelton-wagento mentioned, problems 1 and 2 are separate and would need cloud-docker code bugfixes.

**Comment by carlos-reynosa** [comment]
@YPyltiai  Yes i think so. I provided a documentation recommendation in magento/devdocs#7400 that will resolve number 3.

**Comment by sorinsugar** [comment]
The issue number 3 (host.docker.internal not being available) is been around since we weren't using versioning on containers. On my team, we've overcome this by running this command inside the fpm container:
`echo "$(hostname -i | sed 's/\.[0-9]*$/.1/') host.docker.internal" >> /etc/hosts`
This will fix the issue for linux users without changes to the default compose file. The hostname command is available and returns the current container IP, the sed simply replaces the last number with 1.

**Comment by sorinsugar** [comment]
> One other issue we've encountered related to xdebug settings is the fact the generic service and fpm_xdebug have the same environment variable `PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip redis xsl sodium xdebug`. Meaning that in the end it doesn't matter that we have an dedicated xdebug container if all of the php container are extending generic. The xdebug extenssion should be removed from generic service if we're using dedicated containers running it.

The above seems to have been caused by the fact that xdebug was added in the list on php runtime extensions in .magento.app.yml. I concur that by default fpm_xdebug doesn't enable xdebug.

**Comment by carlos-reynosa** [comment]
I created a doc ticket for number 3 some time ago and there are other related ticket issues:

https://github.com/magento/devdocs/issues/7400#event-3460479386

**Comment by carlos-reynosa** [comment]
This is what i did in order to resolve the issues on linux:

* resolve linux host issue by adding your host IP 
`sed -i -e "s/XDEBUG_CONFIG=remote_host=host.docker.internal/XDEBUG_CONFIG=remote_host=172.17.0.1/g" .docker/config.env  `

* remove ports by line number
`sed -i '111s/.*//' docker-compose.yml && sed -i '112s/.*//' docker-compose.yml  `

* add xdebug module by line number
`sed -i '116s/sodium/sodium xdebug/' docker-compose.yml  `

**Comment by shiftedreality** [comment]
@magento export issue to Jira project MCLOUD as Bug

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-6430) is successfully created for this issue.

**Comment by oshmyheliuk** [comment]
This issue was fixed https://github.com/magento/magento-cloud-docker/pull/282 and will be delivered into `1.2.0`.

For linux systems was added `--set-docker-host` option which will automatically add the `host.docker.internal` entry to the `/etc/hosts` file for the `fpm_xdebug` container.
Also was removed port exposing `'9001:9001'` for xdebug container

**Comment by mercurieus** [comment]
Also experienced that issue on my Linux machine and fix of @carlos-reynosa helps me.
To avoid losing configuration by rewriting `docker-composer.yml` and `.docker/config.env` file (when you'll do next time `ece-docker build:compose` command), I added new configuration to `docker-compose.override.yml`:
```yml
version: '2.1'
    fpm_xdebug:
        environment:
            - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip redis xsl sodium xdebug'
            - 'XDEBUG_CONFIG=remote_host=172.17.0.1 remote_port=9002'
```
Only thing you have to change - set new value of Xdebug listening port at yours IDE: 9002
