### ISSUE TITLE
MCLOUD-6451: Curl call to https from inside containers failing on handshake with v1.1 dockers

### ISSUE THREAD

**Issue by sorinsugar** [magento/magento-cloud-docker#234]
https://jira.corp.magento.com/browse/MCLOUD-6451:
The curl calls from inside the containers trough TLS are failing (OTB magento 2.3.5-p1 and docker images v1.1) is failing at handshake, this causing problems for running mftf over https.

### Steps to reproduce
1. use latest magento2 release
2. Use image versions 1.1
3. Open test container and curl magento trough https

### Expected result
1. Call returns 200

### Actual result
1. Curl fails with this error: curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small

This is because the latest openssl configuration on the PHP containers has this line
`CipherString = DEFAULT@SECLEVEL=2`

Possible fixes:
- Remove the above line from /etc/ssl/openssl.cnf
- Add Ciphers to pound.cfg inside of the ListenHTTPS (eg. `Ciphers "DEFAULT:!DH"`)

**Comment by YPyltiai** [comment]
Hi @sorinsugar , 

Thanks for submitting the bug report. We will review it and get back to you as soon as we can.

Thanks,
Yevhenii

**Comment by mveeramneni** [comment]
@magento export issue to Jira project MCLOUD as Bug

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-6451) is successfully created for this issue.

**Comment by oshmyheliuk** [comment]
Was fixed in this pr https://github.com/magento/magento-cloud-docker/pull/277
Will be released in 1.2.0
