### ISSUE TITLE
MCLOUD-6424: Database directories are not creating automatically

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#235]
https://jira.corp.magento.com/browse/MCLOUD-6424:
### Preconditions

1. Cloud Docker 1.0 is deployed
2. Update to Cloud Docker 1.1

### Steps to reproduce

1. Update to Cloud Docker 1.1

### Expected result

1. Update is successful

### Actual result

```
1. Okay -s just tried to bring up a new 1.1 Docker and got this error :
Status: Downloaded newer image for magento/magento-cloud-docker-php:7.2-cli-1.1
Creating champion_db_1      ... error
Creating champion_elasticsearch_1 ... 
Creating champion_redis_1     ... 
Creating champion_generic_1    ... 
Creating champion_elasticsearch_1 ... done
Creating champion_redis_1     ... done
Creating champion_generic_1    ... done

ERROR: for db Cannot create container for service db: failed to mount local volume: mount /var/www/champion/.docker/mysql/mariadb.conf.d:/var/lib/docker/volumes/champion_mymagento-mariadb-conf/_data, flags: 0x1000: no such file or directory
ERROR: Encountered errors while bringing up the project.
```

**Comment by shiftedreality** [comment]
Workaround:

```
cp -R ./vendor/magento/magento-cloud-docker/dist/mysql .docker &&  cp -R ./vendor/magento/magento-cloud-docker/dist/mysql-quote .docker && cp -R ./vendor/magento/magento-cloud-docker/dist/mysql-sales .docker
```

**Comment by shiftedreality** [comment]
@magento export issue to Jira project MCLOUD as Task

**Comment by shiftedreality** [comment]
@magento export issue to Jira project MCLOUD as Task

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-6424) is successfully created for this issue.

**Comment by lenaorobei** [comment]
:x: Cannot export the issue. This issue is already linked to Jira issue(s): https://jira.corp.magento.com/browse/MCLOUD-6424.

**Comment by lenaorobei** [comment]
:x: Cannot export the issue. This issue is already linked to Jira issue(s): https://jira.corp.magento.com/browse/MCLOUD-6424.

**Comment by lenaorobei** [comment]
:x: Cannot export the issue. This issue is already linked to Jira issue(s): https://jira.corp.magento.com/browse/MCLOUD-6424.

**Comment by lenaorobei** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-7453) is successfully created for this issue.

**Comment by lenaorobei** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-7454) is successfully created for this issue.

**Comment by magento-engcom-team** [comment]
:x: You don't have permission to export issues.

**Comment by magento-engcom-team** [comment]
:x: Cannot export the issue. GitHub repo magento/magento-cloud-docker is not supported in JIRA project PWA and type Task.
