### ISSUE TITLE
Required parameter "name" is not provided

### ISSUE THREAD

**Issue by ipascual** [magento/magento-cloud-docker#237]
### Preconditions
1. Install Magento2 Commerce 2.3.5-p1
2. Install ece-tools 2002.1.1

### Steps to reproduce
1. vendor/bin/ece-docker build:compose --mode="developer" --sync-engine="mutagen" --with-xdebug --expose-db-port=3306

### Expected result
1. docker-composer.yaml created

### Actual result
1.   Required parameter "name" is not provided  
![Screen Shot 2020-06-28 at 10 04 45 AM](https://user-images.githubusercontent.com/1126559/85951148-db751280-b926-11ea-88fc-3c8b0fe726f7.jpg)

**Comment by YPyltiai** [comment]
Hi @ipascual,

I moved the issue to the right repository, since Devbox functionality is developed here.

May you please also confirm version of magento/magento-cloud-docker you use?

Thanks,
Yevhenii

**Comment by ipascual** [comment]
Hi @YPyltiai 

I got the latest version of ece and Magento2, running:
```
composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition magento2
```
I've got:
```
        "magento/ece-tools": "^2002.1",
        "magento/product-enterprise-edition": "2.3.5-p1"
```

**Comment by ipascual** [comment]
Hi @YPyltiai 

**I found the issue**, I required to have:
.magento.app.yaml
.magento/routes.yaml
.magento/services.yaml


before running the command: 
./vendor/bin/ece-docker build:compose --mode="developer" --sync-engine="mutagen" --with-xdebug --expose-db-port=3306 

These files came with cloud configuration, but local development does not have them. It should be detailed under this doc: https://devdocs.magento.com/cloud/docker/docker-development.html
