### ISSUE TITLE
DevBox: project generation

### ISSUE THREAD

**Issue by buskamuza** [magento/magento-cloud-docker#238]
As a developer, I want [Magento Cloud DevBox](https://github.com/magento/catalog-storefront/wiki/Magento-Cloud-DevBox-for-Local-Development) and related tools allow me to easily modify and contribute changes to multiple Magento repositories.

Magento Cloud DevBox is not responsible for project creation. But for git-based development scenarios, [ECE Tools](https://github.com/magento/ece-tools) provide a command `dev:git:update-composer` to generate `composer.json` that takes into account locally cloned repositories. The `composer.json` includes all necessary steps to clone repos when project is initialized, and link repos to Composer. But this approach has some disadvantages, such as recloning repos every time `composer install/update` is run, as well as not symlinking files from repositories.

Goal of this story is to adopt the ECE Tools command that generates `composer.json` for local development workflows.

### AC

1. No recloning of Magento repositories when updating the project
2. Repository files are linked instead of copied, so it's possible to contribute changes back
3. https://github.com/magento/catalog-storefront/wiki/Magento-Cloud-DevBox-for-Local-Development updated to eliminate necessity for `--no-scripts` during second `composer install` command, as recloning of repos should not happen after this story is done.

#### Scenario 1: Initial project setup

Preconditions:

1. Project has `composer.json` generated by updated ece-tools based on `.magento.env.yaml` declarations

Setup project following steps from https://github.com/magento/catalog-storefront/wiki/Magento-Cloud-DevBox-for-Local-Development. 

1. Clone Magento Cloud project repository for specific project. For example, https://github.com/magento/storefront-cloud-project in case of Catalog SF effort
2. Run `composer install --ignore-platform-reqs` to fetch DevBox dependencies
3. Run `docker-compose up -d` to start DevBox
4. Run `./mutagen.sh` to sync file
5. Run `docker-compose run deploy composer install` to update dependencies taking into account real environment
   1. Expected: all repos declared in `composer.json` are cloned inside folders in the project root
   2. Expected: repo files are symlinked to `vendor` and project root folders from repo folders. File modifications are reflected in repos.
6. Run `docker-compose run deploy cloud-deploy` to deploy Magento
7. Run `docker-compose run deploy cloud-post-deploy` to run post-deploy hooks
8. Run `sudo -- sh -c "echo '127.0.0.1 magento2.docker' >> /etc/hosts"` to add DevBox Magento domain to hosts

#### Scenario 2: project update - switching to another branch

Preconditions:

1. Project is cloned locally (for example, https://github.com/magento/storefront-cloud-project)
2. Magento Cloud DevBox is running
3. Target branch has `composer.json` generated by updated ece-tools based on `.magento.env.yaml` declarations

1. Switch project branch
2. Run `docker-compose run deploy composer install`
   1. Expected: all repos declared in `composer.json` are added/updated locally, with branches updated/switched to declared ones
   2. Expected: repo files are symlinked to `vendor` and project root folders from repo folders. File modifications are reflected 

#### Scenario 3: project update - creating new project branch

Preconditions:

1. Project is cloned locally (for example, https://github.com/magento/storefront-cloud-project)
2. Magento Cloud DevBox is running

1. Update `.magento.env.yaml` with necessary repos and branches (add a repo, remove a repo, change a branch in an existing repo)
2. Run ece-tools `dev:git:update-composer` to regenerate the project. See https://github.com/magento/storefront-cloud-project/blob/production/Jenkinsfile#L102-L110 for necessary steps

### Resources

* Prototype with some improvements - https://github.com/magento-architects/ece-tools/tree/ECP-737

### Sub-tasks

* #239 
* #240 
* #241

**Comment by shiftedreality** [comment]
@magento export issue to Jira project MCLOUD as Task

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-6492) is successfully created for this issue.

**Comment by shiftedreality** [comment]
Will be reopened once #283 is completed.
