### ISSUE TITLE
Symlink packages instead of copying

### ISSUE THREAD

**Issue by buskamuza** [magento/magento-cloud-docker#239]
Child of #238 

### Problem statement

The [ECE Tools](https://github.com/magento/ece-tools) provide a command `dev:git:update-composer` command is using `"symlink": false"` option for linking local code from repositories. This makes impossible to commit the changes as the files used in the running application are not linked to the original code anymore. For local development, symlinks should be used instead.

### AC:

* `"symlink": true"` is used for linking files from repositories
* Documentation is updated
   * Any limitations (e.g., repos should be located inside of Magento root) are documented
* Both "production" and "developer" modes of Magento Cloud Docker are running successfully

**Comment by shiftedreality** [comment]
@magento export issue to Jira project MCLOUD as Task

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-6493) is successfully created for this issue.

**Comment by shiftedreality** [comment]
Will be reopened once #283 is completed.
