### ISSUE TITLE
Symlink non-package files

### ISSUE THREAD

**Issue by buskamuza** [magento/magento-cloud-docker#240]
Child of #238 

### Problem Statement

The [ECE Tools](https://github.com/magento/ece-tools) `dev:git:update-composer` command copies files from repos to Magento project root. #133 covers files that can be used from `vendor` directly (clean packages) by using symlinks. Files that are marshaled (copied) to Magento root by Composer plugin need special coverage. Current logic finds all files in each repository that do not belong to any package (don't have a clear folder with `composer.json`) and creates an `rsync` command for them to be copied during `composer install/update`. See `prepare-packages` section in `composer.json` as an example.
The `rsync` command should be replaced/updated so that files are symlinked instead of copied.

### AC

1. Files that are not included in any clear Magento package (module, theme, etc) are symlinked instead of copied during project composition.

**Comment by shiftedreality** [comment]
@magento export issue to Jira project MCLOUD as Task

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-6494) is successfully created for this issue.

**Comment by shiftedreality** [comment]
Will be reopened once #283 is completed.
