### ISSUE TITLE
Preserve already cloned repositories

### ISSUE THREAD

**Issue by buskamuza** [magento/magento-cloud-docker#241]
Child of #238 

### Problem Statement

The [ECE Tools](https://github.com/magento/ece-tools) `dev:git:update-composer` command adds a script to `composer.json` which:

1. Removes all folders with cloned repos (if present)
2. Clone all the repos from scratch

This is inconvenient for local development, as it leads to huge delays in the workflow every time `composer install/update` command is run, every time project repos should be updated (e.g., switching a branch, creating new branch).

### AC

1. The repositories are updated during project update (`composer install/update`)
   1. Repository is unlinked if removed from the project configuration
   2. Repository is linked if added to the project configuration
   3. Branch is switched and dependencies/repos configuration is updated in `composer.json` if changed in the project configuration
2. Git origins are validated and updated if differ from what is declared in the project configuration
3. Branch is switched to what is declared in the project configuration if it differs
4. Repo is updated (Git fetch/pull) when the project is updated
5. Repos declared in project configuration are cloned if not present locally
6. "Reset" scenario is documented, where a developer wants to reset a repo (or all repos) to start from scratch

**Comment by buskamuza** [comment]
"Reset" scenario may be covered by one of (or combination of):

1. Remove folder(s) with repos to be reset before running `composer install/update`
2. Use `git clean` for repository(es) to be reset before running `composer install/update`

**Comment by shiftedreality** [comment]
@magento export issue to Jira project MCLOUD as Task

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-6495) is successfully created for this issue.

**Comment by shiftedreality** [comment]
Will be reopened once #283 is completed.
