### ISSUE TITLE
301-302 permanent redirect problem in my project

### ISSUE THREAD

**Issue by alinolandry** [magento/magento-cloud-docker#242]
I set up my magento cloud development environment using docker. 
I used the documentation procedure and here is the docker file compose generate as an attachment.
All my containers are going well;
Database connections are fine;
the core_config_data table has been modified for the local url;
the site works well on my cloud environments but in local, I have 302 redirects; I don't know what is causing the problem any more.
I checked on varnish, nginx, php-fpm, htacesss, logs etc ...
I don't know what to do, I need help please

My docker-compose.yml

`version: '2'
services:
  db:
    image: 'mariadb:10.0'
    environment:
      - MYSQL_ROOT_PASSWORD=top_local
      - MYSQL_DATABASE=top_local
      - MYSQL_USER=top_local
      - MYSQL_PASSWORD=top_local
    hostname: db.magento2.docker
    ports:
      - '3306'
    networks:
      magento:
        aliases:
          - db.magento2.docker
    volumes:
      - 'magento-db:/var/lib/mysql'
      - '.docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
      - '.docker/mnt:/mnt'
  redis:
    image: 'redis:5.0'
    volumes:
      - /data
    ports:
      - 6379
    networks:
      - magento
  elasticsearch:
    image: 'magento/magento-cloud-docker-elasticsearch:6.5-1.0'
    networks:
      - magento
  rabbitmq:
    image: 'rabbitmq:3.7'
    networks:
      - magento
  fpm:
    image: 'magento/magento-cloud-docker-php:7.2-fpm-1.0'
    extends: generic
    ports:
      - 9000
    depends_on:
      - db
    volumes:
      - './:/app:rw'
      - './vendor:/app/vendor:rw'
      - './generated:/app/generated:rw'
      - './var:/app/var:delegated'
      - './app/etc:/app/app/etc:delegated'
      - './pub/media:/app/pub/media:delegated'
      - './pub/static:/app/pub/static:delegated'
    networks:
      - magento
  build:
    image: 'magento/magento-cloud-docker-php:7.2-cli-1.0'
    extends: generic
    hostname: build.magento2.docker
    depends_on:
      - db@localhost
      - redis
      - elasticsearch
      - rabbitmq
    volumes:
      - './:/app:rw'
      - './vendor:/app/vendor:rw'
      - './generated:/app/generated:rw'
      - '~/.composer/cache:/root/.composer/cache:delegated'
    networks:
      magento-build:
        aliases:
          - build.magento2.docker
  deploy:
    image: 'magento/magento-cloud-docker-php:7.2-cli-1.0'
    extends: generic
    hostname: deploy.magento2.docker
    depends_on:
      - db
      - redis
      - elasticsearch
      - rabbitmq
    volumes:
      - './:/app:rw'
      - './vendor:/app/vendor:rw'
      - './generated:/app/generated:rw'
      - './var:/app/var:delegated'
      - './app/etc:/app/app/etc:delegated'
      - './pub/media:/app/pub/media:delegated'
      - './pub/static:/app/pub/static:delegated'
      - '~/.composer/cache:/root/.composer/cache:delegated'
      - './.docker/mnt:/mnt'
    networks:
      magento:
        aliases:
          - deploy.magento2.docker
  web:
    image: 'magento/magento-cloud-docker-nginx:latest-1.0'
    extends: generic
    hostname: web.magento2.docker
    depends_on:
      - fpm
    volumes:
      - './:/app:rw'
      - './vendor:/app/vendor:rw'
      - './generated:/app/generated:rw'
      - './var:/app/var:delegated'
      - './app/etc:/app/app/etc:delegated'
      - './pub/media:/app/pub/media:delegated'
      - './pub/static:/app/pub/static:delegated'
    networks:
      magento:
        aliases:
          - web.magento2.docker
  varnish:
    image: 'magento/magento-cloud-docker-varnish:latest-1.0'
    environment:
      - VIRTUAL_HOST=top.local
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
    ports:
      - '80:80'
    depends_on:
      - web
    networks:
      magento:
        aliases:
          - magento2.docker
  tls:
    image: 'magento/magento-cloud-docker-tls:latest-1.0'
    ports:
      - '443:443'
    external_links:
      - 'varnish:varnish'
    depends_on:
      - varnish
    networks:
      - magento
  generic:
    image: alpine
    environment:
      - PHP_MEMORY_LIMIT=2048M
      - UPLOAD_MAX_FILESIZE=64M
      - MAGENTO_ROOT=/app
      - PHP_IDE_CONFIG=serverName=magento_cloud_docker
      - XDEBUG_CONFIG=remote_host=host.docker.internal
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip redis xsl'
volumes:
  magento:
    driver_opts:
      type: none
      device: '${PWD}'
      o: bind
  magento-vendor:
    driver_opts:
      type: none
      device: '${PWD}/vendor'
      o: bind
  magento-generated:
    driver_opts:
      type: none
      device: '${PWD}/generated'
      o: bind
  magento-db: {  }
  magento-var:
    driver_opts:
      type: none
      device: '${PWD}/var'
      o: bind
  magento-app-etc:
    driver_opts:
      type: none
      device: '${PWD}/app/etc'
      o: bind
  magento-pub-media:
    driver_opts:
      type: none
      device: '${PWD}/pub/media'
      o: bind
  magento-pub-static:
    driver_opts:
      type: none
      device: '${PWD}/pub/static'
      o: bind
  docker-mnt:
    driver_opts:
      type: none
      device: '${PWD}/.docker/mnt'
      o: bind
networks:
  magento:
    driver: bridge
  magento-build:
    driver: bridge`

**Comment by YPyltiai** [comment]
Hi @alinolandry,

Would you be able to confirm that base URL used for Docker, the one in hosts file and the one in Magento DB do match across the board? Most commonly redirects are cause by miss-match, when you web server tries to use URL different to one specified in Magento itself.

Thanks,
Yevhenii

**Comment by shiftedreality** [comment]
@alinolandry is it still actual?

**Comment by alinolandry** [comment]
Hello @shiftedreality  @YPyltiai ,
Sorry for time, I solve my problem. I also send this problem in the magento slack community. 
For here, The problem was the hostname, I changed it, and try to use default hostname(magento2.docker) when you setup your local environement with docker and evereything works well.

Thank you.
