### ISSUE TITLE
Add .env file parsing for Environment Variables

### ISSUE THREAD

**Issue by aepod** [magento/magento-cloud-docker#248]
Docker provides for Environment Variables, and Magento Cloud uses them as well. Magento Cloud Docker could use .env file to populate environment variables inside the containers. This is in addition to the ability to do this from the docker-compose files, because it would be for secrets for populating the env.php or other things like that. 

https://devdocs.magento.com/cloud/env/variables-cloud.html

Variables such as these oftentimes have "secret" values such as env.php crypt key. This would allow for setting these outside of repositories and have the values populate in the containers as you would expect, based on the Magento Cloud variables.

**Comment by shiftedreality** [comment]
@magento export issue to Jira project MCLOUD as Task

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-6429) is successfully created for this issue.

**Comment by oshmyheliuk** [comment]
Hi @aepod ,
We already have `.env` file: `.docker/config.env` for populating environment variables inside containers.

Isn't it enough for your needs?

**Comment by aepod** [comment]
It could be, but we should support this: https://docs.docker.com/compose/environment-variables/#the-env-file

which would be at the root directory. The file you are referring to also is "auto-generated" by the compose command, which means it should not really be edited or added to.

**Comment by oshmyheliuk** [comment]
You can pass custom environment variables into the `build:compose` command by using an option `--env-vars` and they will be saved into `.docker/config.env` so they will be available in containers.
https://devdocs.magento.com/cloud/docker/docker-config.html#set-the-environment-variables.

The `.env` file in the root directory is supported by default in docker but is only used during a pre-processing step when working with docker-compose.yml files. 

For example, we have two files:
`.env`
```
DB_VERSION=10.3
```
`docker-compose.yaml`
```yaml
services:
  db:
    image: 'mariadb:${DB_VERSION}'
```
In this case, DB_VERSION only replaces the value in docker-compose.yaml and not be available in containers.
So, to use `.env` file we need to put some placeholders ${VARIABLE_NAME} into docker-compose.yaml, but I don't know what exactly it should be.

**Comment by aepod** [comment]
Oh that is interesting, I had not considered that. Let me think about it, I
will respond soon.

**Comment by oshmyheliuk** [comment]
@aepod Hi,
I'm closing this issue for now.
Please feel free to reopen if you will have any suggestions.
