### ISSUE TITLE
Test Git/JIRA sync

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#249]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by shiftedreality** [comment]
@magento export issue to Jira project MCLOUD as Task

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-6427) is successfully created for this issue.
