### ISSUE TITLE
dh key too small when trying to use magento-cloud-docker-tls

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento-cloud-docker#257]
I had **magento/magento-cloud-docker-tls:latest-1.1* container running for SSL offloading. When I used the "*magento/magento-cloud-docker-php:7.4-fpm-1.1**" container (Debian Buster) to curl https://tls.magento2.docker, I received the error below.

error:141A318A:SSL routines:tls*process_ske*dhe:dh key too small

To work around the issue, I had to remove "**CipherString = DEFAULT@SECLEVEL=2**" from the /etc/ssl/openssl.cnf file. I believe the SSL key might be too small in the Magento SSL certificate in the magento-cloud-docker-tls docker image.

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MCLOUD-6469

**Comment by shiftedreality** [comment]
Done in https://github.com/magento/magento-cloud-docker/pull/273
