### ISSUE TITLE
ps library is missing on newer images

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#259]
ps is required for Magento command, and it must present in Docker PHP images

### Steps to reproduce

1. Pull new images
2. Run any PS command inside PHP container

### Expected result

1. No errors

### Actual result

1. ps command is not availble

**Comment by shiftedreality** [comment]
@magento export issue to Jira project MCLOUD as Bug

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-6621) is successfully created for this issue.
