### ISSUE TITLE
Build container not accessing Redis

### ISSUE THREAD

**Issue by Axel29** [magento/magento-cloud-docker#275]
Hello,

I've installed magento-cloud-docker for the first time but can't seem to get it 100% working due to the build container impossibility to connect to Redis.

Due to this issue, I cannot run some commands like `docker-compose run --rm build cloud-build`.

### Preconditions
1. Magento Cloud 2.4.0
2. Redis for sessions and cache storage
3. magento-cloud-docker

### Steps to reproduce
1. Run any Magento command with build container (example: `docker-compose run --rm build magento-command list`)

### Expected result
1. Magento displayed the full list of available commands

![image](https://user-images.githubusercontent.com/3015249/90227788-6ea1d300-de15-11ea-8d25-1a8fda30c938.png)

### Actual result
1. The following error is thrown because of unreachable Redis server:

> Connection to Redis redis:6379 failed after 2 failures.Last Error : (1) php_network_getaddresses: getaddrinfo failed: Name or service not known

![image](https://user-images.githubusercontent.com/3015249/90227965-b9234f80-de15-11ea-9278-76e281f1951f.png)

**Comment by shiftedreality** [comment]
Hello, build container does not have an access to Redis by design. Please use `deploy` container instead

**Comment by Axel29** [comment]
Hello @shiftedreality,

Then how can we run the `bin/magento-docker ece-build` or `bin/magento-docker ece-redeploy` command?
It fails with the same error on module:enable --all command...

**Comment by shiftedreality** [comment]
`ece-build` does not require Redis connection. The Magento Cloud architecture does not have any services during the build phase, so if anything requires it - it should fail on both Cloud and Cloud Docker

**Comment by Axel29** [comment]
@shiftedreality if I'm not mistaken, one of the steps from `vendor/magento/ece-tools/scenario/build/generate.xml` is `Magento\MagentoCloud\Step\Build\RefreshModules` which triggers a `php ./bin/magento module:enable --all --ansi --no-interaction` that triggers the error `The command "php ./bin/magento module:enable --all --ansi --no-interaction" failed. Connection to Redis redis:6379 failed after 2 failures.Last Error : (1) php_network_getaddresses: getaddrinfo failed: N
  ame or service not know`

![image](https://user-images.githubusercontent.com/3015249/90258381-c0b01c00-de48-11ea-8541-31fa96565319.png)

**Comment by shiftedreality** [comment]
That's correct, but Magento itself does not require Redis during module enabling. and it's a serious issue if it would. My assumption that you may have some 3rd-party module that is doing this. Have you tried deploying it on Cloud?

**Comment by Axel29** [comment]
I've tried to remove the usage of Redis in my app/etc/env.php file and it works without it, or at least now it breaks on the database connection (`SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o
  r service not known`), so it seems to me that it's not due to a module but simply because bin/magento uses the env.php file, which is configured to use Redis.
But even without redis it blocks on the database connection too.

**Comment by shiftedreality** [comment]
Thanks, that makes more sense then.

It looks like this happens if you run full re-build and re-deploy instead of re-deploy only.

1. You should not have `app/etc/env.php` during the initial installation.
2. You should use `ece-deploy` to redeploy the environment if there are no module changes.

I have some ideas on how to get it fixed, thanks for reporting!

**Comment by shiftedreality** [comment]
@magento export issue to Jira project MCLOUD as Bug

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-6732) is successfully created for this issue.

**Comment by aepod** [comment]
The build container should NOT have app/etc/env.php, this file needs to be
moved aside if you want the container to properly work.

It will work as intended without this file.

**Comment by Axel29** [comment]
Okay I get it, since it was in the ece-redeploy alias, I thouught I was better to run it too.
Thank you for your help.
