### ISSUE TITLE
Add ece-docker build:compose command as comment in docker-compose.yml

### ISSUE THREAD

**Issue by aepod** [magento/magento-cloud-docker#287]
After generating the docker-compose.yml it is sometimes hard to remember the exact command that was used.

To solve this we can add a comment on line 2 of the docker-compose.yml that stores the ece-docker build:compose command.

Example:
```
version: '2.1'
# vendor/bin/ece-docker build:compose --php=7.4 --es=7.6 --mode=developer --sync-engine=native
services:
[snip rest of file]

```
This was proposed on the cloud docker slack channel.

**Comment by YPyltiai** [comment]
@magento export issue to Jira project MCLOUD as Story

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-6874) is successfully created for this issue.

**Comment by shiftedreality** [comment]
Added in https://github.com/magento/magento-cloud-docker/commit/83bdb0d2dc339c31f6dbd274e04403f05123e0b5
