### ISSUE TITLE
Mailhog container "restart: always"

### ISSUE THREAD

**Issue by joeshelton-wagento** [magento/magento-cloud-docker#291]
Prerequisite: My daily routine with a Mac workstation is to logout/login. This causes Docker daemon to restart daily. (The issue may also be caused by the fact that I work with multiple project environments during a typical day.)

The mailhog container is set to `restart: always` . This leads to start/stop behavior inconsistent with the rest of the containers. Most of the time when I start up an environment, it looks like this:

```
[09:50:51] joeshelton@local /Volumes/ProjectFiles/busdepot$ docker-compose up -d
Starting busdepot_generic_1 ... 
Starting busdepot_db_1      ... 
Starting busdepot_elasticsearch_1 ... 
Starting busdepot_mailhog_1       ... 
Starting busdepot_mailhog_1       ... error
Starting busdepot_generic_1       ... done
Starting busdepot_db_1            ... done
Starting busdepot_elasticsearch_1 ... done
 busdepot_mailhog_1 (d9e4ca7e3365e0f67de5c7304affd14283f3cff9b8422602530efdb1cf925aa9): Bind for 0.0.0.0:8025 failed: poStarting busdepot_redis_1         ... done
```

This is caused by the mailhog container having already started when Docker daemon previously started, separate from the other containers in the environment.

In addition to the inconsistency with other containers in an environment, the `restart: always` setting doesn't seem compatible with multiple project environments. If I'm working with 3 different projects, do 3 different mailhog containers attempt to start when the Docker daemon restarts?

The `restart: always` setting seems like a failsafe mechanism appropriate for a production environment. Or, perhaps in a queue consumer scenario? It does not seem appropriate for development environments/modes.

**Comment by NadiyaS** [comment]
@magento export issue to Jira project MCLOUD as Bug

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-6917) is successfully created for this issue.

**Comment by BaDos** [comment]
Will be delivered in this PR https://github.com/magento/magento-cloud-docker/pull/290
