### ISSUE TITLE
Application environment variable does not contain mounts

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#292]
### Preconditions

1. Cloud Docker cloned
2. .docker/config.php.dist is present
3. .magento.app.yaml is presnt

### Steps to reproduce

1. Check the content of config.php.dist

### Expected result

1. The file contains MAGENTO_CLOUD_APPLICATION variable with content from `.magento.app.yaml`

### Actual result

1. The file contains MAGNTO_CLOUD_APPLICATION with incomplete content from `.magento.app.yaml`:

```
    'MAGENTO_CLOUD_APPLICATION' => base64_encode(json_encode([
        'hooks' => [
            'build' => 'set -e

php ./vendor/bin/ece-tools build:generate
php ./vendor/bin/ece-tools build:transfer
',
            'deploy' => 'cat .magento.app.yaml > var/debug.log
php ./vendor/bin/ece-tools deploy
',
            'post_deploy' => 'php ./vendor/bin/ece-tools post-deploy
'
        ]
    ])),
```

### Related items

* Revert the temporary fix introduced in https://github.com/magento/ece-tools/pull/781

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by chiranjeevi-cj** [comment]
@shiftedreality Is this issue in the wrong repo? Because the changes were made in the ece-tools repo. Can you please verify that? Thanks!

**Comment by chiranjeevi-cj** [comment]
@shiftedreality Any update?

**Comment by shiftedreality** [comment]
@chiranjeevi-cj this is the correct repo since we moved all logic related to MCD into this repository

**Comment by chiranjeevi-cj** [comment]
@shiftedreality I can't able to find the temporary fix(https://github.com/magento/ece-tools/blob/40566cb609b2330fdfaafcb9b7f08f05619e2960/src/Config/EnvironmentData.php#L146-L153)

`/**
         * Temporary fix for the case when environment data does not accurately represent file configuration.
         *
         * @url https://github.com/magento/magento-cloud-docker/issues/292
         */
        if (!isset($applicationEnvConfig['mounts']) && isset($applicationFileConfig['mounts'])) {
            $applicationEnvConfig['mounts'] = $applicationFileConfig['mounts'];
        }
`

Can you specify the branch in which this fix is present? 

Thanks!

**Comment by shiftedreality** [comment]
It should be in the latest `developer` branch, the idea was that ECE-Tools can read `.magento.app.yaml`. But actually, it should not be used, since Cloud Docker should be able to properly pass them via environment variables

**Comment by shiftedreality** [comment]
Merged
