### ISSUE TITLE
elasticsearch max_map_count issue

### ISSUE THREAD

**Issue by sivamind** [magento/magento-cloud-docker#305]
elasticsearch_1  | ERROR: [1] bootstrap checks failed
elasticsearch_1  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elasticsearch_1  | [2021-02-01T03:54:53,577][INFO ][o.e.n.Node               ] [XE6UvKt] stopping ...
elasticsearch_1  | [2021-02-01T03:54:53,702][INFO ][o.e.n.Node               ] [XE6UvKt] stopped
elasticsearch_1  | [2021-02-01T03:54:53,702][INFO ][o.e.n.Node               ] [XE6UvKt] closing ...
elasticsearch_1  | [2021-02-01T03:54:53,720][INFO ][o.e.n.Node               ] [XE6UvKt] closed
elasticsearch_1  | [2021-02-01T03:54:53,724][INFO ][o.e.x.m.j.p.NativeController] [XE6UvKt] Native controller process has stopped - no new native processes can be started
xyz_elasticsearch_1 exited with code 78
xyz_build_1 exited with code 0

Host OS - windows 10
magento/magento-cloud-docker-elasticsearch:6.5-1.2.1
steps to reproduce 
docker-compose up -d

**Comment by sivamind** [comment]
magento/magento-cloud-docker-elasticsearch:6.5-1.2.1

**Comment by aepod** [comment]
https://devdocs.magento.com/cloud/docker/docker-containers-service.html#troubleshooting

This is a known issue in Windows, it is not a Magento Cloud Docker bug.
