### ISSUE TITLE
ece-tools file could not open in windows 10

### ISSUE THREAD

**Issue by sivamind** [magento/magento-cloud-docker#306]
C:\newdock>docker-compose run --rm deploy cloud-deploy
Creating newdock_deploy_run ... done                                                                                                                                    Running "deploy" hook.
Could not open input file: ./vendor/bin/ece-tools
returned non-zero exit status 1

even i tried composer require magento/ece-tools. but still same issue.

**Comment by sivamind** [comment]
if i'm using  ./vendor/bin/ece-docker build:compose --mode="developer" --sync-engine="mutagen" its not working.I installed mutagen as well.
if i use with out any sync tool its working

./vendor/bin/ece-docker build:compose --mode="developer"

**Comment by sivamind** [comment]
Please consider Windows OS as well, i think there is a issue with symlinks in windows.
 instead of ./vendor/bin/ece-tools how to call ./vendor/magento/ece-tools/bin/ece-tools?

**Comment by sivamind** [comment]
$ mutagen sync list
-------------------------------------------------------------------------------
Identifier: sync_8nwXc820VgxIvIOBwxipgmX72tQueXzCXnM0LJgPeri
Labels:
        magento-docker-vendor: <empty>
Alpha:
        URL: C:\xyz\kim\vendor
        Connection state: Connected
Beta:
        URL: docker://12c2cb65dc0384f234d1d9be6f9e9474a070422304a14ed76a9a7ac09ba31e3b/app/vendor
                DOCKER_HOST=
                DOCKER_TLS_VERIFY=
                DOCKER_CERT_PATH=
                DOCKER_API_VERSION=
        Connection state: Connected
Status: Waiting 5 seconds for rescan
Last error: alpha scan error: unable to open file (bin/carbon): unable to open file handle: path pointed to symbolic link
-------------------------------------------------------------------------------

**Comment by aepod** [comment]
Magento Cloud Docker does not work well with Windows, except in the context of WSL2. If you install WSL2, enable hyper-v and install ubuntu as a WSL vm, and Docker Desktop in windows. You can then use ubuntu vm to manage the docker compose stuff, have native linux there so you do not even need a sync engine. 
This works very well, and really is the only performant and easy way to handle this in windows.

**Comment by sivamind** [comment]
@aepod wsl2 and ubuntu installed ,Now its working fine.Thank you
