### ISSUE TITLE
magento 2.4.2 supports composer 2 version

### ISSUE THREAD

**Issue by sivamind** [magento/magento-cloud-docker#308]
How to use composer 2 instead of composer 1 version?

**Comment by sivamind** [comment]
also can u add varnish 6.4 version

**Comment by YPyltiai** [comment]
@shiftedreality , please see this request.

**Comment by shiftedreality** [comment]
Composer 2 added in the latest release.
Doc updates PR: https://github.com/magento/devdocs/pull/8893

Please create a separate issue for Varnish update request
