### ISSUE TITLE
[FEAT]: Static Version-Controllable Configuration to mitigate long, tedious commands.

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento-cloud-docker#309]
**Is your feature request related to a problem? Please describe.**
The current setup of constantly requiring `build:compose` on every release (or even within the life-cycle of a release) is painful. 

I often find myself perusing docs that I don't want to peruse because I don't remember some  `--with-entrypoint`  -like command.

Right now, I have to frequently explain flags to devs of various seniorities every release, which is terribly painful.

**Describe the solution you'd like**
Please provide a `cloud-docker.json` or something so that I don't have to constantly remember all the various flags. 
Potentially, a `cloud-docker.default.json` would also be version-controllable by the team so that each team can have their own default `build:compose`.

**Describe alternatives you've considered**
None.

**Additional context**
No.

**Comment by YPyltiai** [comment]
Thanks for creating an issue @damienwebdev ! As per Slack discussion - looks like this feature exists but lacks documentation. We will merge documentation and see if anything else is missing.

**Comment by shiftedreality** [comment]
Assigned to me for documentation release

**Comment by shiftedreality** [comment]
PR is being processed https://github.com/magento/devdocs/pull/8728

**Comment by shiftedreality** [comment]
PR was delivered documentation is avaialble: https://devdocs.magento.com/cloud/docker/docker-config-sources.html#unified-configuration

Thank you for bringing this up.
