### ISSUE TITLE
In product listing page sort price by ascending not working

### ISSUE THREAD

**Issue by rajubytes** [magento/magento-cloud-docker#311]
**Preconditions**
In product listing page price sorting not working with ascending order 

**Steps to reproduce**
Step1. Add 10 to 12 simple product and add 5 to 7 configurable product (add some simple product & configurable product with zero price).
Step2. Goto storefront and navigate to product listing page.
Step3. Select "price" from sort by dropdown (it's redirect current page with asc sorted order)
Step4. Product displaying with incorrect sort order

**Expected result**
In our case product starting with zero(0.00) price.

**Actual result**
It's display products starting price with greater than 0 

![category_list](https://user-images.githubusercontent.com/53551805/109494920-8b051480-7ab4-11eb-8d5c-ae3b015af139.png)

**Comment by YPyltiai** [comment]
Hi @rajubytes,

Did you identify this being specific to Cloud Docker? It looks like a general Magento problem, which is not related to the Docker environments. It may need to be moved to https://github.com/magento/magento2 repository.

Thanks,
Yevhenii
