### ISSUE TITLE
PHP Opcache is overcaching files in developer mode

### ISSUE THREAD

**Issue by aepod** [magento/magento-cloud-docker#312]
### Preconditions
1.  Developer mode, with native filesync
2. WSL2 enabled docker (may affect macs too)
3. Default php.ini, no changes to opcache settings

### Steps to reproduce
1. Bring up docker
2.  Change phtml template
3. Clear magento caches
4. changes do not reflect

### Expected result
1. Changes get reflected.

### Actual result
1. Changes are not shown.
Also of note, you can restart containers with docker-compose down && docker-compose up. This will then reflect the changes.

### Cause
Opcache is toggled on and no file changes are being checked.
Reseting opcache or invalidating also fixes this.

**Comment by YPyltiai** [comment]
@aepod , wasn't it fixed with latest version? It looks very familiar.

**Comment by shiftedreality** [comment]
Fixed in latest version
