### ISSUE TITLE
init-docker.sh not being released as an asset in tagged releases

### ISSUE THREAD

**Issue by mjdurham** [magento/magento-cloud-docker#313]
### Preconditions

1. Trying to follow with the magento docs https://devdocs.magento.com/cloud/docker/docker-installation.html

### Steps to reproduce

1. Follow the last step at the bottom of [docker installation docs](https://devdocs.magento.com/cloud/docker/docker-nstallation.html)  This tells you to run:

 `curl -sL https://github.com/magento/magento-cloud-docker/releases/download/1.2.0/init-docker.sh | bash -s -- --php 7.4`

2. That url gives you a 404

### Expected result

1. The docker `init-docker.sh` should be a bundled asset in the 1.2.x builds or the docs should be updated reflect changes

### Actual result

1. I have to roll back to version 1.1.1 or use the raw url `https://raw.githubusercontent.com/magento/magento-cloud-docker/1.2.1/bin/init-docker.sh`

**Comment by shiftedreality** [comment]
Thank you for reporting this.

Assigning to @oshmyheliuk to release a binary file

**Comment by oshmyheliuk** [comment]
Created ticket for required changes

**Comment by oshmyheliuk** [comment]
Done, please check.
