### ISSUE TITLE
Paypal express was not working with cancel discount code in cart page.

### ISSUE THREAD

**Issue by rajubytes** [magento/magento-cloud-docker#316]
**Preconditions**
Paypal express was not working with cancel discount code in cart page.

**Steps to reproduce**
Step 1. Set UK as merchant country 
Step 2. Configure Paypal express with sandbox account.  
Step 3. Added to cart 1 product with without login customer.
Step 4. Apply discount code from cart page.
Step 5. Remove discount code
Step 6. Click on Paypal express button.
 

**Expected result**
1. Paypal express popup should be display.

**Actual result**
1. Paypal express popup not display and given warning message "To check out, please sign in with your email address."

Screen with apply discount code
![Applied Discount code](https://user-images.githubusercontent.com/53551805/114978983-b6e32a80-9ea7-11eb-8b3a-a5322acec3ad.png)

Screen with remove discount code
![Remove Discount code](https://user-images.githubusercontent.com/53551805/114979084-e09c5180-9ea7-11eb-842e-550432b6ab62.png)

Screen with paypal warning message
![Paypal warning message](https://user-images.githubusercontent.com/53551805/114979148-fad62f80-9ea7-11eb-998d-7552aad8a166.png)

**Comment by YPyltiai** [comment]
Hi @rajubytes,

Did you identify this being specific to Cloud Docker? It looks like a general Magento problem, which is not related to the Docker environments. It may need to be moved to https://github.com/magento/magento2 repository.

Thanks,
Yevhenii
