### ISSUE TITLE
Hardcoded magento.com in the CN name in the ssl certificate

### ISSUE THREAD

**Issue by slitviachenko** [magento/magento-cloud-docker#320]
### Preconditions
1. Magento Cloud Docker 1.2.2

### Steps to reproduce
1. Install any supported Magento with the default Magento Cloud Docker configuration.
2. Try to open https://magento2.docker/ in a browser or via `curl` cli.

### Expected result
1. https://magento2.docker/ opens (as it was in the 1.2.1 version).

### Actual result
1. The "NET::ERR_CERT_INVALID" error appears.

It looks like in this commit https://github.com/magento/magento-cloud-docker/commit/761e44c52b5d978e136e8e052e6916bd801397a5 **"magento.com"** was hardcoded.
The `--host` option of the `ece-docker build:compose` command is ignored.

**Comment by shiftedreality** [comment]
@oshmyheliuk could you review this?

**Comment by oshmyheliuk** [comment]
I'll test and create a task to fix it if needed.

**Comment by slitviachenko** [comment]
@oshmyheliuk , thank you. Need to use a host name specified in the `--host` option, and the default value for the CN should be `magento2.docker` I believe, as it is the default in other places too.

**Comment by oshmyheliuk** [comment]
@slitviachenko Are you sure this is an issue with hardcoded `CN=magento.com`?
The previous certificate which was stored in the `certs/` directory had hardcoded `CN` as well.

**Comment by slitviachenko** [comment]
@oshmyheliuk , when I switch to Magento Cloud Docker 1.2.1, everything works fine, the issue is on 1.2.2 only, I receive the "NET::ERR_CERT_INVALID" error, and my google chrome indicates the name mismatch.

**Comment by slitviachenko** [comment]
@oshmyheliuk , "magento2.docker" is used as a default everywhere except the certificate.

**Comment by slitviachenko** [comment]
@oshmyheliuk , I verified that deleted certificate had "magento2.docker" in the CN that is why I don't have an issue on 1.2.1.

**Comment by oshmyheliuk** [comment]
@slitviachenko Thank you for the update

**Comment by oshmyheliuk** [comment]
@slitviachenko I can confirm that problem exists, but changing `CN=magento.com` to `CN=magento2.docker` didn't resolve it. I've created a task to investigate and fix it.

**Comment by slitviachenko** [comment]
@oshmyheliuk , on **1.2.1** I get the "NET::ERR_CERT_AUTHORITY_INVALID" error because the certificate is self-signed, but that is expected. The name mismatching error is more critical.

**Comment by oshmyheliuk** [comment]
@slitviachenko I tried to solve this issue but didn't find a way how to generate a certificate that will be trusted in the Chrome browser.

`The name mismatching error is more critical.` -  this is not a reason why the certificate is untrusted, changing CN to `magento2.docker`  doesn't solve a problem. 

There are several solutions:
1) If you are using Chrome browser and there is no button to ignore certificate error just type `thisisunsafe` and you will proceed as usual
2) There is a button to ignore certificate error in the Firefox browser
3) If you are using CURL just add `-k` or `--insecure` option

We can't use the previous certificate from 1.2.1 as it is already expired and maybe this is a reason why Google Chrome allows us to ignore the error.

Please feel free to reopen this issue if you have proposals on how to resolve it in a better way.

**Comment by slitviachenko** [comment]
@oshmyheliuk , Could you please fix [the CN name](https://github.com/magento/magento-cloud-docker/blob/develop/images/nginx/1.19/Dockerfile#L26)? It seems the only difference between the previous certificate and the current one is that CN name (and the expiration date, but I don't believe that the correct date could be the reason). With 1.2.2 MFTF tests stopped working due to the certificate issues.
