### ISSUE TITLE
Latest releases no longer include init-docker.sh as asset

### ISSUE THREAD

**Issue by MagicLegend** [magento/magento-cloud-docker#356]
### Steps to reproduce

1. Follow the documentation at https://developer.adobe.com/commerce/cloud-tools/docker/setup/initialize-docker/
2. Realise the curl command is outdated, and try to update the version to 1.3.4 (latest as of writing)
3. Curl will fail

### Expected result

1. The latest release version of `init-docker.sh` should be ran

### Actual result

1. Curl fails

**Comment by BaDos** [comment]
@MagicLegend thank you for your contribution!

The internal task was created to fix it.

**Comment by MagicLegend** [comment]
Perhaps the documentation should just point to the `latest` version instead of a version as well? That might also prevent issues down the road where versions used in the docs are unsupported.

Regardless, the releases here on Github should include the `init-docker.sh` file as an asset (which was my intention with the issue). Thank you for the quick response!

**Comment by BaDos** [comment]
@MagicLegend I will check the documentation, thank you!

All releases were fixed:
https://github.com/magento/magento-cloud-docker/releases/tag/1.3.4
https://github.com/magento/magento-cloud-docker/releases/tag/1.3.3
https://github.com/magento/magento-cloud-docker/releases/tag/1.3.1
