### ISSUE TITLE
Problems with Adobe Live Search on Local docker containers | 503 Varnish backend fetch failed

### ISSUE THREAD

**Issue by pisicabogdan** [magento/magento-cloud-docker#365]
### Preconditions
1. Magento Cloud Docker with PHP 8.2
2. OpenSearch 2.4
3. Nginx 1.19
4. Varnish 6.6

### Steps to reproduce
First, I upgraded some existing packages:

- upgraded the magento/product-recommendations composer module from 5.0.1 to 6.0.2
- upgraded the magento/module-page-builder-product-recommendations module from 2.0.1 to 2.0.4
- upgraded the magento/module-visual-product-recommendations from 2.0.1 to 2.0.4

Then:
1. Update the API keys from the Magento Admin for SaaS
2. Install Adobe Live Search version 4.1.2 following the documentation: https://experienceleague.adobe.com/en/docs/commerce-merchant-services/live-search/install through composer: `composer require magento/live-search`
3. Disable OpenSearch/ElasticSearch modules: `bin/magento module:disable Magento_Elasticsearch Magento_Elasticsearch7 Magento_OpenSearch Magento_ElasticsearchCatalogPermissions Magento_InventoryElasticsearch Magento_ElasticsearchCatalogPermissionsGraphQl`
4. Run `bin/magento setup:upgrade`
5. Run sync catalog data bin/magento commands

### Expected result
The site should load correctly and Live Search should be functional.

### Actual result
On a branch of Adobe Cloud, everything works as expected.

The specific issue I encounter happens only on my local DEV environments, the official docker containers:
![WebsiteCrashError](https://github.com/magento/magento-cloud-docker/assets/92723115/ea2fb402-73c2-4eca-b8f2-b8e7018ebc06)

I created a ticket on Adobe Commerce Support but their answer was that they don't deal with local environments, even if the official images are used.

Is there anyone who has installed Live Search on the local environment, in which they have Adobe Sensei activated at the same time?

Thanks in advance!

**Comment by andriyShevtsov** [comment]
# 4. Run bin/magento setup:upgrade

That needs to be corrected.  You can't simply run setup:upgrade. Please check step 4 here https://developer.adobe.com/commerce/cloud-tools/docker/deploy/production-mode/

**Comment by pisicabogdan** [comment]
> # 4. Run bin/magento setup:upgrade
> That needs to be corrected. You can't simply run setup:upgrade. Please check step 4 here https://developer.adobe.com/commerce/cloud-tools/docker/deploy/production-mode/
Hello!

Thanks for the reply. I will try.

Question: even if magento is set to developer mode, do I need to rebuild the docker images?

**Comment by pisicabogdan** [comment]
> # 4. Run bin/magento setup:upgrade
> That needs to be corrected. You can't simply run setup:upgrade. Please check step 4 here https://developer.adobe.com/commerce/cloud-tools/docker/deploy/production-mode/

It seems that it doesn't work even with this solution.

**Comment by andriyShevtsov** [comment]
@pisicabogdan  Internal ticket was created  MCLOUD-12387

**Comment by pawelrox** [comment]
@andriyShevtsov is there an update on this issue? We are currently exploring Adobe Live Search but cannot because this issue is a blocker.

**Comment by pisicabogdan** [comment]
Hello,

I solved the problem. The error appears when the Content Security Policy header is longer than the limit imposed in varnish. After I disabled the custom CSP, the website worked.
