### ISSUE TITLE
[Cloud Docker Core] DB data should persist in a volume

### ISSUE THREAD

**Issue by joeshelton-wagento** [magento/magento-cloud-docker#41]
For those that don't know the difference between stopping and downing a container, DB data should be stored in a volume. This prevents accidental data loss.

### Preconditions
Development is in progress on a working docker environment with a DB previously imported.

### Steps to reproduce
`docker-compose down`

### Expected result
`docker-compose up` would restore the development environment with DB data persisted from last dev session.

### Actual result
A new "blank" DB container is created. DB changes from previous dev sessions lost.

**Comment by mattskr** [comment]
I'm not sure if this is an actual issue. We always use docker-compose stop which does preserve the data. Probably better documentation is all that is needed to explain the difference between the two. Having both options (stop and down) are most useful depending on a developers workflow and preference.

**Comment by YPyltiai** [comment]
https://github.com/magento/magento-cloud-docker/pull/92
Let's move discussion to PR above ^. We need to decide if that's the flow to go with or if it just needs some additional documentation
