### ISSUE TITLE
[Cloud Docker Core] Exclude large files from docker-sync

### ISSUE THREAD

**Issue by joeshelton-wagento** [magento/magento-cloud-docker#42]
When first starting `docker-sync`, the period of inactivity experienced by syncing any large files (>1 GB) creates the impression that something may be wrong. Large files like DB dumps and archives are unnecessary to sync. Add the following file types to the default ignore section of `docker-sync.yaml`:

- *.sql
- *.gz
- *.zip
- *.bz2

### Preconditions
First run of `docker-sync`. A DB dump file downloaded using `magento-cloud db:dump` exists in the project root.

### Steps to reproduce
`docker-sync start`

### Expected result
DB dumps and other large files should be ignored by the sync.

### Actual result
The wait is long while syncing the DB dump.

**Comment by shiftedreality** [comment]
Fixed in https://github.com/magento/magento-cloud-docker/pull/84
Closed.
