### ISSUE TITLE
Give us the ability to have multiple projects with different volumes

### ISSUE THREAD

**Issue by LucasCalazans** [magento/magento-cloud-docker#43]
When we're trying to use multiple projects using the docker environment we receive an error because the volume name is fixed in some files.

### Preconditions
1. I've tried with Linux OS (More specifically Fedora 30)

### Steps to reproduce
1. Mount a project using docker environment (Developer mode)
2. After that, try to create another one using the same architecture

### Expected result
1. Both projects should work with no error

### Actual result
1. We face an error because they are sharing the same volume so Magento is already installed when we try to install again
2. It brokes exactly when we try to execute `docker-compose run deploy cloud-deploy`

### Solutions
I had to change manually some files with a different `sync` name, like this:
```bash
PROJECT_NAME="project2"
SYNC_NAME="${PROJECT_NAME}-sync"
sed -i -E "s/(.*)magento-sync(.*)/\1${SYNC_NAME}\2/" ./docker-compose.yml ./docker-sync.yml ./vendor/magento/ece-tools/src/Docker/Compose/DeveloperCompose.php
```

I think that a `.env` file could be a good solution

**Comment by joeshelton-wagento** [comment]
This is a daily issue for me, as well. I use a solution similar to @LucasCalazans

**Comment by aepod** [comment]
This can be solved by using the app name from the .magento.app.yaml as a prefix for the magento-sync drive. If done per project, this will alleviate the conflict.
