### ISSUE TITLE
[Cloud Docker Core] Warm-up not Working Properly on Post-deploy Phase in Docker

### ISSUE THREAD

**Issue by YPyltiai** [magento/magento-cloud-docker#44]
Internal ID: `MAGECLOUD-3939`

**We don't currently support warm-up during the post-deploy hook in Docker implementation. This is past of ECE-Tools post-deploy process and has to be fixed.**

**To Do:**
* Fix warm-up process to properly warm-up pages without errors in Cloud Docker implementation

**Comment by shiftedreality** [comment]
Fixed in `1.0` branch.
Closed.
