### ISSUE TITLE
[Cloud Docker Core] Set Varnish as Default Cache

### ISSUE THREAD

**Issue by YPyltiai** [magento/magento-cloud-docker#46]
Internal ID: `MAGECLOUD-3598`

**Background:**
- Currently on Cloud Docker we set up Varnish by default but do not configure it properly
- Since traffic is still going through it, we get a number of unexpected issues

**To Do:**
- Set up Varnish as default cache instead of MySQL for Cloud Docker

**Comment by shiftedreality** [comment]
Internal task: https://magento2.atlassian.net/browse/MAGECLOUD-3598

**Comment by YPyltiai** [comment]
Resolved by #97 97
