### ISSUE TITLE
Add New OOTB Technology Stack Parts

### ISSUE THREAD

**Issue by YPyltiai** [magento/magento-cloud-docker#47]
Internal ID: `MAGECLOUD-3243`

**As** a Magento developer, **I want** local dev solution to be working OOTB without me configuring additional technical stack parts, **so** it's easy and fast to set environment up.

**To Do:**
* Consider adding some Docker-native way to build the stack (PHP + Composer to avoid setting up anything natively besides Docker)
* Capability to isolate dev dependencies natively for production mode

**Comment by shiftedreality** [comment]
Internal task: https://magento2.atlassian.net/browse/MAGECLOUD-3243

**Comment by aepod** [comment]
If the application is in a normal checked out state, but without composer or php or any services. It is possible to bring the app up and build the docker containers with the following command:
```
docker run -it  -v $(pwd):/app/ -v ~/.composer/:/root/.composer/ magento/magento-cloud-docker-php:7.3-cli-1.1 bash -c "composer install && ./vendor/bin/ece-docker build:compose --mode developer && chown -R `stat -c "%u:%g" .` /app"
```
1) Assumes ~/.composer/auth.json exists (needed for checking out magento etc)
2) Assumes the project has the cloud docker files that are from the cloud template (.magento.app.yaml etc)
3) Installs using composer
4) Runs the ece-docker build command
5) Cleans up file permissions

This command uses the standard magento-cloud-docker image, and the "version" has to be tagged: `magento/magento-cloud-docker-php:7.3-cli-1.1` so it is a little tricky there too, some users would want to use php 7.2 or 7.1 and these image tags may change over time. We may want to think about adding a metatag to the dockerhub for php73 php74 etc, just major versions, or ones that match with the php versions so they do not have to keep searching out 1.1 etc.


This can be scripted easily, but I would suggest at least for now just adding this to the documentation in the implementing cloud docker section. This can be explained enough so developers can use this to script in Jenkins or on local workstations.

Additionally, we should think about adding this as a script to the cloud template repository, like the .magento.app.yaml it is a prerequisite in the repository for this to work.

**Comment by michaelcasey316** [comment]
I've created a draft pull request in the magento-cloud template repository here: https://github.com/magento/magento-cloud/pull/444

**Comment by YPyltiai** [comment]
Duplicate of #148
