### ISSUE TITLE
An Egg & Chicken problem

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#49]
Hello, Community

I would like to describe one problem came during developing https://github.com/magento/magento-cloud-docker/pull/31

In nutshell, we want to get closer to the real Cloud environment and introduce `web:web` user instead of `root`.

I will skip technical details, but essentially there will be 2 sets of PHP images:
`php-{cli|fpm}-{version}` and `php-{cli|fpm}-{version}-dev`, where `-dev` images will represent developer environment.

The problem is hidden in Docker Hub versioning policy and ECE-Tools publication process.

Imagine, we'll deliver new `-dev` images to Hub and this will break current Docker setups because the latest version of ECE-Tools won't know anything about `-dev` images. And the new version of `non-dev` images won't run in Developer mode anymore.

To be able to generate `docker-compose.yml` file properly according to images, we moved all Docker functionality to https://github.com/magento/magento-cloud-docker

This will essentially be released as a new Composer package `magento/magento-cloud-docker:1.0.0` let's call it MCD

In result, we will get into one of 2 situations:

- **A**: Release MCD without new images. This will not break current setups, but MCD package won't be useful.
- **B**: Release images first, which will break Dev setups, and only fix will be to manually add `-dev` to php images or require MCD package (which is not obvious) or update to a newer version of ECE-Tools with MCD dependency included.
- **C**: Stop automatic Docker Hub images publication from the `master`. Switch to `MCD <=> Hub` versioning policy. Where images will be versioned like `magento/magento-cloud-docker-php:7.1-1.0.0`

**Comment by 00F100** [comment]
suggestion: make now MCD (non-dev) with version 1.0.0 and after add (-dev) up version to 2.0.0?

**Comment by shiftedreality** [comment]
Images are currently not aligned with MCD version, they're building on merge to `master` branch trigger. Seems like it won't help.

**Comment by joeshelton-wagento** [comment]
I like C. Now that you have MCD in a separate package, you can rev it whenever you want. And I think coupling the images and code will create more compatibility between the two.

**Comment by YPyltiai** [comment]
Agree with Joe on option C. I told that during grooming but adding it here for visibility too.

**Comment by shiftedreality** [comment]
Makes sense then. Will proceed with option **C**.

Thank you, guys!
