### ISSUE TITLE
[Cloud Docker Core] Mutagen Creates Multiple Stale Sessions

### ISSUE THREAD

**Issue by aepod** [magento/magento-cloud-docker#55]
### Preconditions
1. Have run mutagen.sh
2.  Subsequent runs create multiple mutagen sessions

### Steps to reproduce
1.  Set up docker with mutagen
2.  Run mutagen.sh
3.  Rerun mutagen.sh

### Expected result
1. Session would be recreated

### Actual result
1.  More than one session is created, old ones are stale

>[webuser@localhost project-m2]$ ./mutagen.sh
>Created session c75abb45-74ad-4cf0-ab3b-d3c51bf65a7a
>[webuser@localhost project-m2]$ ./mutagen.sh
>Created session bf2a3f2b-815b-43d3-9b9c-fafd806a6bfb
>[webuser@localhost project-m2]$ mutagen sync list
>--------------------------------------------------------------------------------
>Identifier: c75abb45-74ad-4cf0-ab3b-d3c51bf65a7a
>Labels: None
>Alpha:
>        URL: /home/webuser/docker/project-m2
>        Connection state: Connected
>Beta:
>        URL: docker://e87016098b2bedfc25da6fd35ad9c5e7dd2eaacc104711765a2399866c6a7bb3/app
>                DOCKER_HOST=
>                DOCKER_TLS_VERIFY=
>                DOCKER_CERT_PATH=
>        Connection state: Connected
>Status: Scanning files
>--------------------------------------------------------------------------------
>Identifier: bf2a3f2b-815b-43d3-9b9c-fafd806a6bfb
>Labels: None
>Alpha:
>        URL: /home/webuser/docker/project-m2
>        Connection state: Connected
>Beta:
>        URL: docker://e87016098b2bedfc25da6fd35ad9c5e7dd2eaacc104711765a2399866c6a7bb3/app
>                DOCKER_HOST=
>                DOCKER_TLS_VERIFY=
>                DOCKER_CERT_PATH=
>        Connection state: Connected
>Status: Scanning files
>--------------------------------------------------------------------------------

**Comment by shiftedreality** [comment]
Hello @aepod,

Thank you for reporting this issue.
I've created an internal ticket https://magento2.atlassian.net/browse/MAGECLOUD-4410 to fix it.

**Comment by aepod** [comment]
1) Add tagged name to Mutagen instance: https://mutagen.io/documentation/introduction/names-labels-identifiers/
2) Enhance mutagen.sh, check for and prompt for removal of old sessions

This is my plan, I am working on this, feel free to put it in progress and assign to me @shiftedreality

**Comment by shiftedreality** [comment]
Fixed in https://github.com/magento/magento-cloud-docker/pull/127
