### ISSUE TITLE
[Cloud Docker Core] Add Possibility to Use Custom nginx.conf with Cloud Docker

### ISSUE THREAD

**Issue by YPyltiai** [magento/magento-cloud-docker#60]
**Background:**
* There is a need for users to apply custom Nginx configurations for their Cloud Docker environments
* Currently Cloud Docker uses hard-coded configurations

**To Do:**
* Add possibility to mount custom nginx.conf to Cloud Docker environments

**Comment by shiftedreality** [comment]
Internal issue: https://magento2.atlassian.net/browse/MAGECLOUD-4204

Closed.

**Comment by ryanjavens** [comment]
Hey @YPyltiai and @shiftedreality . I noticed this was closed but was hoping to get some more details on this. Was this implemented and is there any documentation around how to use a custom Nginx config? Thank you!

**Comment by shiftedreality** [comment]
Hello,

We'll update DevDocs with next instruction:

1. Create folder ./.docker/nginx/etc/ and place configs
2. Replace variables like `!UPLOAD_MAX_FILESIZE!;` to appropriate values in file vhost.conf
3. Add lines to volumes section of `web` container:

```
- './.docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf'
- './.docker/nginx/etc/vhost.conf:/etc/nginx/conf.d/default.conf'
```

Let us know if that helps

**Comment by ryanjavens** [comment]
Thank you so much @shiftedreality !
