### ISSUE TITLE
[MFTF Integration] Add Selenium Image to run MFTF on Local Machine with Similar to Cloud Environment

### ISSUE THREAD

**Issue by YPyltiai** [magento/magento-cloud-docker#61]
**To Do:**
* Consider adding Selenium image with pre-configured MFTF to run MFTF tests against Cloud Docker environment locally

**Comment by shiftedreality** [comment]
Internal task: https://magento2.atlassian.net/browse/MAGECLOUD-4040

**Comment by shiftedreality** [comment]
Fixed in https://github.com/magento/magento-cloud-docker/pull/89
