### ISSUE TITLE
Provide an Option to Specify Custom Base URL for Magento Cloud Docker

### ISSUE THREAD

**Issue by YPyltiai** [magento/magento-cloud-docker#62]
**To Do:**
* Add possibility to specify custom base URL for Magento Cloud Docker installation

**Comment by shiftedreality** [comment]
Internal task: https://magento2.atlassian.net/browse/MAGECLOUD-4545

**Comment by aandolg** [comment]
@magento I am working on it

**Comment by shiftedreality** [comment]
Added in https://github.com/magento/magento-cloud-docker/pull/163
