### ISSUE TITLE
[Cloud Docker Core] Mutagen or docker-sync not needed on Linux

### ISSUE THREAD

**Issue by mattskr** [magento/magento-cloud-docker#69]
Docker on Linux does not need 3rd party file syncing utilities as binding a host directory to a container does not suffer from the same performance issues as Windows or macOS

### Preconditions

1. build docker environment on a Linux to generate docker-compose.yml file.

### Steps to reproduce

1. Start and deploy the Docker do not use docker-sync or mutagen
2. Make change to your code, you will not see the change on the site.

### Expected result
1. docker-compose that is generated with the magento-sync volume as a bind type.
2. Changes on host will be immediately reflected in fpm container.

### Actual result
1. Cannot use the docker cloud on Linux without using mutagen or docker-sync (slower and unnecessary) or modifying the docker-compose.yml manually.

**Comment by shiftedreality** [comment]
Hello @mattskr

We've created internal task https://magento2.atlassian.net/browse/MAGECLOUD-4351 to fix this issue.

**Comment by shiftedreality** [comment]
Added in https://github.com/magento/magento-cloud-docker/pull/64 as `sync-engine="native"` option.
