### ISSUE TITLE
[Cloud Docker Core] Add ionCube Support

### ISSUE THREAD

**Issue by mattskr** [magento/magento-cloud-docker#70]
Environments on cloud support the ionCube Loader but developers do not have it locally.

### Preconditions

1. Add ioncube to the list of extensions in .magento.app.yaml file.

### Steps to reproduce
1.  Start or deploy your environment 

### Expected result
1. Should see that ioncube is loaded when you run php -v on the fpm container.

### Actual result
1. php -v does not show that ionCube is installed.
2. Have to manually install it or else encrypted php code will not execute.

**Comment by YPyltiai** [comment]
Should be manageable like other PHP extensions in current implementation.

@arhiopterecs / @bbatsche / @shiftedreality , please review.

**Comment by shiftedreality** [comment]
It looks like we don't have this supported. Added task https://magento2.atlassian.net/browse/MAGECLOUD-4354

**Comment by YPyltiai** [comment]
Will be resolved as part of https://github.com/magento/magento-cloud-docker/pull/72
