### ISSUE TITLE
PHP Extension bcmath is not Available for PHP 7.3

### ISSUE THREAD

**Issue by hanyws** [magento/magento-cloud-docker#74]
**Steps to reproduce:**
* Install ECE-Tools `2002.0.21`
* Run `./vendor/bin/ece-tools docker:build`

**Expected Behavior:**
* Config is created successfully

**Actual Behavior:**
* Error `PHP extension bcmath is not available for PHP version 7.3.` is displayed

**Comment by YPyltiai** [comment]
@andriyShevtsov , @mveeramneni , please validate

**Comment by andriyShevtsov** [comment]
In case if I use  ece-tools command `./vendor/bin/ece-tools docker:build  --php=7.3` i got next error:
```
In PhpExtension.php line 187:

  PHP extension bcmath is not available for PHP version 7.3.
  PHP extension bz2 is not available for PHP version 7.3.
  PHP extension calendar is not available for PHP version 7.3.
  PHP extension exif is not available for PHP version 7.3.
  PHP extension gd is not available for PHP version 7.3.
  PHP extension gettext is not available for PHP version 7.3.
  PHP extension intl is not available for PHP version 7.3.
  PHP extension mysqli is not available for PHP version 7.3.
  PHP extension pcntl is not available for PHP version 7.3.
  PHP extension pdo_mysql is not available for PHP version 7.3.
  PHP extension soap is not available for PHP version 7.3.
  PHP extension sockets is not available for PHP version 7.3.
  PHP extension sysvmsg is not available for PHP version 7.3.
  PHP extension sysvsem is not available for PHP version 7.3.
  PHP extension sysvshm is not available for PHP version 7.3.
  PHP extension opcache is not available for PHP version 7.3.
  PHP extension zip is not available for PHP version 7.3.
  PHP extension redis is not available for PHP version 7.3.
  PHP extension xsl is not available for PHP version 7.3.
  PHP extension json is not supported.
  PHP extension sodium is not available for PHP version 7.3.

```

Command `vendor/bin/ece-docker  build:compose --php=7.3 `works correct

**Comment by andriyShevtsov** [comment]
@hanyws please  add to required section:   
`"magento/magento-cloud-docker": "1.0.x-dev as 1.0.99",`
and run` vendor/bin/ece-docker build:compose --php=7.3 `instead of ` ./vendor/bin/ece-tools docker:build --php=7.3`

**Comment by shiftedreality** [comment]
Requested extension is available in `1.0` branch.
Please re-open if closed by mistake.

**Comment by hanyws** [comment]
> @hanyws please add to required section:
> `"magento/magento-cloud-docker": "1.0.x-dev as 1.0.99",`
> and run`vendor/bin/ece-docker build:compose --php=7.3`instead of ` ./vendor/bin/ece-tools docker:build --php=7.3`

Problem 1
    - The requested package magento/magento-cloud-docker could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

**Comment by andriyShevtsov** [comment]
@hanyws Do you have docker in repo section:
```
        "docker":{
            "type": "vcs",
            "url": "git@github.com:magento/magento-cloud-docker.git"
          }
```
