### ISSUE TITLE
Linux First docker-compose Architecture

### ISSUE THREAD

**Issue by aepod** [magento/magento-cloud-docker#75]
The docker:build command is problematic, in that it sets up dependencies for the environment in which you are running it for. With Mac or Windows you have very specific requirements for making the containers work properly. Currently when you run docker:build it generates all these requirements and puts them in the docker-compose.yaml file. 

Ideally this process would work slightly differently.  Instead you would generate docker-compose.yaml with as minimal amount is needed to run it on all systems(linux), and any requirements that are specific would go into environment configs:
docker-compose-mac.yaml
docker-compose-windows.yaml

This still leaves docker-compose.override.yaml alone, which you should so that developers can make any final changes for their specific environment easily. 

This would allow a different workflow, where the docker-compose files can be checked into the repository and version controlled. When the docker:build command is run it can update each of these environment override files.

Another adjustment that would be need to happen is to allow for people to boot up the proper overrides when they do the docker-compose up -d, this can be in the documentation and also in the _./bin/docker start_ command.

With this architecture you can support ALL three linux, mac and PC with the same set of docker-compose files, and not have to switch back and forth when you are in a different environment. This is very common because these same docker containers should be used by jenkins or circleci etc, to run the smoke tests, run unit tests and a variety of other tasks.

The goal here is to have the same containers through out the entire development stack, and also to be able to version the docker-compose files so that you can support multiple environments at the same time.

**Comment by shiftedreality** [comment]
Internal issue: https://magento2.atlassian.net/browse/MAGECLOUD-4457

**Comment by mattskr** [comment]
if you do this I think you need to have people use the ./bin/docker start command which will load up the correct overrides for you and if on Mac/windows also start mutagen.

**Comment by andriyShevtsov** [comment]
@aepod Please provide status of this isuue

**Comment by aepod** [comment]
Doing review of this, looking at 1.1.0 in develop branch, alongside what we have done. The --native flag which was already added actually did a lot of what was required for this, but I am double-checking everything. I will have an update early next week.

**Comment by shiftedreality** [comment]
Thanks for your contributions!

Closed.
