### ISSUE TITLE
Document Docker Services/Containers and Request Flow

### ISSUE THREAD

**Issue by aepod** [magento/magento-cloud-docker#76]
### Preconditions
Current Documentation on Docker:  https://devdocs.magento.com/guides/v2.3/cloud/docker/docker-development.html
There is no documentation of the containers/services.  

Current List of Services:
- build
- deploy
- cron
- db
- elasticsearch
- redis
- rabbitmq
- tls
- varnish
- web
- fpm

### Steps to reproduce
Docker documentation is missing detailed service definitions. There is no request flow diagram and it is hard to understand the internal workings of each of the containers without documentation. Most containers have some amount of configuration that can be done using 
 configuration files.

### Expected result
Detailed service definitions, for each of the containers that include any configuration that can be done. Pages that do exist like configuring Xdebug, or connecting to the database should probably be moved under the proper service container headers as well.

There are all sorts of useful things like changing out what modules are being loaded, changing configuration of the services and so on that can be done using the existing containers. All of this should have a more structured home, and should be easy to add to the documentation.

In addition to the service containers, there is also the request flow to help people understand how to debug.  ie. tls->varnish->web->php-fpm. Additional information about debugging, or customizing the request flow will naturally fit here.

**Comment by YPyltiai** [comment]
@meker12 , @hguthrie , please review this request.

**Comment by shiftedreality** [comment]
Internal task: https://magento2.atlassian.net/browse/MAGECLOUD-4450

**Comment by meker12** [comment]
Documentation updates merged into the Docker-1.0.0 integration branch in PR https://github.com/magento/devdocs/pull/6363.

**Comment by YPyltiai** [comment]
@aepod , I guess we can treat this one as done?

**Comment by aepod** [comment]
Still missing the image build commands, I will get a PR into devdocs for
that tomorrow, sorry for the delay.
