### ISSUE TITLE
Container Healthchecks

### ISSUE THREAD

**Issue by aepod** [magento/magento-cloud-docker#77]
Docker containers do not have health checks, so you can run commands before the services are ready. Adding a healthcheck allows for automation around the standup of the application, because currently there is a wait period while db and elasticsearch and phpfpm are ready.

https://docs.docker.com/engine/reference/builder/#healthcheck
These can be used in docker-compose: https://docs.docker.com/compose/compose-file/#healthcheck

Having this on services like elasticsearch, db and fpm would be great.

Here is a guide on the process for php-fpm: https://github.com/renatomefi/php-fpm-healthcheck

Even just having this on the fpm container would be a huge improvement, because this is the last container to come up and be ready.

**Comment by shiftedreality** [comment]
Internal issue: https://magento2.atlassian.net/browse/MAGECLOUD-4456

**Comment by YPyltiai** [comment]
ES health-check added in #113
We now need to add the rest - #116
