### ISSUE TITLE
Open up port 3306 for Database

### ISSUE THREAD

**Issue by aepod** [magento/magento-cloud-docker#80]
This is an easy fix, will include a PR in a bit.

### Preconditions
1. Current docker-compose doesn't expose 3306

### Steps to reproduce
1. Bring up docker
2. Notice the port is not exposed using docker-compose ps

### Expected result
1. It should look like this
>magento-m2_db_1              docker-entrypoint.sh mysqld      Up       0.0.0.0:3306->3306/tcp

### Actual result
1. Not exposed
>magento-m2_db_1              docker-entrypoint.sh mysqld      Up

**Comment by shiftedreality** [comment]
Internal task: https://magento2.atlassian.net/browse/MAGECLOUD-4544

**Comment by mattskr** [comment]
@shiftedreality you can assign this one to me.

**Comment by drpayyne** [comment]
Hi, I've identified that changing `3306` to `'3306:3306'` at this line https://github.com/magento/ece-tools/blob/2ee01049914502d9aab5213dd399fc50c32645d4/src/Docker/Compose/ProductionCompose.php#L105 exposes the database port. How I proceed on this? Is this the right approach to expose the port? And shall I create a PR in the ece-tools repository as a fix?

Thanks.

**Comment by mattskr** [comment]
@shiftedreality see above comment

**Comment by shiftedreality** [comment]
@drpayyne @mattskr I think adding an option like `ece-docker build --expose-db-port 3306` would make it more flexible. 

Please let me know your thoughts, the change should be made in this repo, as ECE-Tools does not contain Docker builder anymore.

**Comment by aepod** [comment]
Adding the options makes a lot of sense, in some cases you may not want to
expose it. (host already has mysql running on port 3306)

**Comment by mattskr** [comment]
@drpayyne let's add the flag as @shiftedreality suggested.

**Comment by shiftedreality** [comment]
Fixed in https://github.com/magento/magento-cloud-docker/pull/101
