### ISSUE TITLE
adding magento/magento-cloud-docker to composer error

### ISSUE THREAD

**Issue by hanyws** [magento/magento-cloud-docker#82]
"magento/magento-cloud-docker": "1.0.x-dev as 1.0.99",

in equired section of composer.json

get error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/magento-cloud-docker could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by YPyltiai** [comment]
@hanyws , did you add the Git repo into repositories section? Since this package is not yet released, you need to pull from GitHub directly.

This is not a bug, likely some miss-configuration. Please contact us on Slack, we'll help to configure it.

Thanks!
