### ISSUE TITLE
Add possibility to build from sources

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#93]
To improve the developer's experience, we should add an option `--from-sources` which will point `docker-compose` to image sources instead of published images. This will give a possibility to properly and easily test changes into images locally.

### Preconditions

1. Cloud Docker is installed
2. Cloud project is cloned

### Expected result

1. Cannot build from sources

### Actual result

1. Option with building from sources added

**Comment by shiftedreality** [comment]
Internal issue: https://magento2.atlassian.net/browse/MAGECLOUD-4573

**Comment by YPyltiai** [comment]
Discussed with @aepod in Slack - it appears to be simple to do that with current setup but it requires documentation. Thus transferring it from development task to documentation one.

**Comment by aepod** [comment]
Documentation PR https://github.com/magento/devdocs/pull/6408
