### ISSUE TITLE
Add possibility to preserve existing docker-compose.yml

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#94]
### Preconditions

1. Cloud project cloned
2. Cloud Docker compose file generated

### Steps to reproduce

1. Add custom changes to `docker-compose.yml`
2. Run `./vendor/bin/ece-docker build:compose`

### Expected result

1. Custom changes preserved

### Actual result

1. File content fully replaced

**Comment by shiftedreality** [comment]
Internal ticket: https://magento2.atlassian.net/browse/MAGECLOUD-4580

**Comment by drpayyne** [comment]
Hi @shiftedreality, out of curiosity, would custom changes override and ignore incoming changes from `ece-docker build:compose`?

**Comment by shiftedreality** [comment]
We could use `docker-compose*.yml` native merging mechanism, so `./bin/magetno-docker` commands should grep all files and merge them on to of default `docker-compose.yml`:

i.e:

```
 docker-compose -f docke-compose.yml -f docke-compose-custom.yml down --volumes
```

**Comment by drpayyne** [comment]
Hi @shiftedreality, please assign this to @mattskr (or me) as well. Thanks!

**Comment by shiftedreality** [comment]
@drpayyne assigned to you. For some reason, Matt is absent in assignee dropdown for this particular issue

**Comment by drpayyne** [comment]
Thanks anyways!

**Comment by drpayyne** [comment]
Hi @shiftedreality, please review the PR: https://github.com/magento/devdocs/pull/6035 in regard to this issue. Thanks!

**Comment by hguthrie** [comment]
Regarding DevDocs, there is a release branch for Docker there.
https://github.com/magento/devdocs/tree/Cloud-Docker-1.0.0

**Comment by drpayyne** [comment]
Hi @shiftedreality, I'm under the impression that the `docker-compose.override.yml` file is autopicked up. Any other custom file, for example, `docker-compose-windows.yml` should be manually provided. Since there's a small quirk when supplying `-f` argument to `docker-compose` that, all files starting with base configuration, including the override configuration (otherwise auto picked up) should also be manually specified. What do you think?

**Comment by shiftedreality** [comment]
If that's auto-picked (sorry, didn't know that) - I'm good with that

**Comment by drpayyne** [comment]
Yes, `docker-compose.override.yml` is auto picked. But if we want to specify any other named configuration, we'll have to specify _all_ configurations, including base, override, and custom.

**Comment by drpayyne** [comment]
Could this ticket be closed as the documentation for this is accepted in DevDocs?

**Comment by shiftedreality** [comment]
Thank you,
Closed.
