### ISSUE TITLE
Build container isolation

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#99]
`build` container should not access to services like `db`, `redis`, etc to emulate Cloud.

### Preconditions

1. Project is cloned
1. Containers are up

### Steps to reproduce

1. SSH into `build` container `docker-compose run build bash`
2. Curl `db` container `curl db:3306`

### Expected result

1. Connection refused, as DB container not available

### Actual result

1. Container is avaible

**Comment by shiftedreality** [comment]
Need to collect the info about the case where developers doing FS changes on the build phase.

**Comment by mattskr** [comment]
@aepod would taking away any of these services from build container cause issues in your project's workflows?

**Comment by mattskr** [comment]
@shiftedreality what would be the suggested way to deny access to these containers? Should we create a separate user-defined network in Docker-compose and only put the build container on it?

Our developer has also found that there are networking differences between the compose files created in ece-docker versus what is in ece-tools. Ece-tools has no networks explicitly defined, but ece-docker defines one called 'magento'.

**Comment by shiftedreality** [comment]
Yeah, without defining networks it won't be possible to access containers by the domain name.

ie: Deploy container runs warm-up using `magento2.docker`.

I was able to solve this task by adding new network like `magento-build` and using it for `build` container only

**Comment by mattskr** [comment]
ok, do you want us to continue working on it or will you just commit your solution?

**Comment by shiftedreality** [comment]
Please continue, I just experimented with already generated `docker-compose.yml`, but not coding itself

**Comment by shiftedreality** [comment]
Internal task: https://magento2.atlassian.net/browse/MAGECLOUD-4834

**Comment by aepod** [comment]
I think this is a great change. It may make it slightly harder to use the
build container for things other than "building" but we can always use the
main fpm container or even add another container instead of using the build
container for running magento commands etc.

It will be a change to the workflow, I think it is a welcome change, given
that this makes it identical to the cloud build process.

**Comment by shiftedreality** [comment]
PR is merged, thank you for your contribution!
